### ISSUE TITLE
Can't start scrapyd with systemd on Ubuntu 15.04

### ISSUE THREAD

**Issue by aguegu** [scrapy/scrapyd#102]
``` bash
# service scrapyd start
# Failed to start scrapyd.service: Unit scrapyd.service failed to load: No such file or directory.
```

It is the Upstart issue with ubuntu 15.04, which switch upstart to systemd.

Just as same as the mongo 3.0+ service broken on ubuntu 15.04. 

But mongo got a tricky workaround to install the debian repo, not ubuntu repo:

https://stackoverflow.com/questions/29879231/upgrade-to-ubuntu-15-04-from-14-10-breaks-mongo-how-to-fix/29930925?stw=2#29930925

Wonder if there is any workaround.

**Comment by ubooksapp** [comment]
First, make sure that the service you are trying to run is installed in your machine, you can list all available services using below command:
```shell
systemctl list-units --type=service
```
luck!
