### ISSUE TITLE
Update ubuntu packages

### ISSUE THREAD

**Issue by gmeans** [scrapy/scrapyd#103]
Can we get the ubuntu packages updated?

I have a scrapy issue I'm trying to resolve that appears to require 1.0.3 to function correctly. I tried deploying this version with the latest scrapyd but I don't think the current scrapyd release works with the latest scrapy version (per other issues, and my own experience).

Should we not rely on the Ubuntu packages and instead opt for pip?

**Comment by boogheta** [comment]
There was apparently a new version uploaded yesterday on ubuntu's repository.
Does that mean this is finally handled and will be updated in the future?
cc @Digenis

**Comment by boogheta** [comment]
my bad, I dreamt apparently, my updater told me so just because I did an install from an older version this week, forget i said anything :/

**Comment by jpmckinney** [comment]
I don't believe a scrapyd Ubuntu package is being maintained (anymore) by this project.
