### ISSUE TITLE
Scrapyd configuration when installing from pip or Github

### ISSUE THREAD

**Issue by mediix** [scrapy/scrapyd#104]
I thought I'd throw this in here.
When installing from pip or straight the github page. Where does scrapyd picks up the configuration settings. 
I installed the latest from Github repo, then created "/etc/scrapyd/scrapyd.conf" put some setting in there. But scrapyd doesn't seem to pick it up from there. 
Any help would be appreciated.

**Comment by Digenis** [comment]
According to https://github.com/scrapy/scrapyd/blob/1fce99b7c285b23dddc2fedc19c815fc4830581f/scrapyd/config.py#L29-L32
you put the config in the right place.

My guess is that the user running scrapyd
doesn't have the necessary permissions to access it.
(`glob.glob()` as seen above doesn't raise exceptions for these things)

If this is the case, confirm it here and close this issue;
You may be interesting in reading about umask.

**Comment by Digenis** [comment]
Closing because of insufficient info
