### ISSUE TITLE
spiders length is 0

### ISSUE THREAD

**Issue by brucewinger** [scrapy/scrapyd#107]
When setting LOG_STDOUT=True, scrapyd-deploy will return 'spiders: 0'. Because the output will be redirected to the file when execute 'scrapy list', like this: INFO:stdout:spider-name. So  `get_spider_list` can not parse it correctly.

**Comment by Digenis** [comment]
https://github.com/scrapy/scrapyd/blob/2357bd53c8b538203a6a0114419fc4cab5dcf855/scrapyd/utils.py#L105-L117 looks funny.
Which version of scrapy do you use?
This probably broke in the update of the logging mechanism.

Why does scrapy need `LOG_STDOUT=True` in the first place?
Has not `LOG_FILE=/dev/stdout` solved this already decades ago?

**Comment by nkubarelov** [comment]
Thanks for this comment here. It took me 2 days debugging why I got 'spiders: 0' when trying to deploy. Commenting LOG_STDOUT fixed for me. Thanks again!

**Comment by Digenis** [comment]
Scrapy ticket: https://github.com/scrapy/scrapy/issues/1646

**Comment by jpmckinney** [comment]
Closing in favor of Scrapy ticket.
