### ISSUE TITLE
Unhandled error in Deferred when running scrapyd using "start scrapyd"

### ISSUE THREAD

**Issue by jatinder85** [scrapy/scrapyd#110]
```
2015-09-27 08:59:12 [scrapy] INFO: Scrapy 1.0.3 started (bot: scraper)
2015-09-27 08:59:12 [scrapy] INFO: Optional features available: ssl, http11
2015-09-27 08:59:12 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'scraper.spiders', 'SPIDER_MODULES': ['scraper.spiders'], 'FEED_URI': 'file:///home/scrapy/scrapyd/items/default/google/054acb1664f611e59938020eb1232813.jl', 'LOG_FILE': '/home/scrapy/scrapyd/logs/default/google/054acb1664f611e59938020eb1232813.log', 'BOT_NAME': 'scraper'}
2015-09-27 08:59:12 [scrapy] INFO: Enabled extensions: CloseSpider, FeedExporter, TelnetConsole, LogStats, CoreStats, SpiderState
2015-09-27 08:59:12 [twisted] CRITICAL: Unhandled error in Deferred:
2015-09-27 08:59:12 [twisted] CRITICAL: 
```

Version:
Scrapy (1.0.3)
scrapyd (1.1.0)

FYI: The scraping works when I run scrapyd as root using "sudo scrapyd"

**Comment by Digenis** [comment]
We 'll need more information.
You missed the scrapyd log.

By `start scrapyd`, do you mean `service scrapyd start`?

Scrapy is not meant to be ran as root.
You should have a scrapy user for the daemon.
How did you install scrapyd?
Have you checked the directory permissions?

**Comment by Digenis** [comment]
I encounter the same error when a spider middleware throws an exception.
In scrapyd it shows the above while in the shell it shows the error, with loglevel 'error'.

**Comment by jatinder85** [comment]
@Digenis  Thanks for the response. I am running scrapy and scrapyd as root on ubuntu in a ec2 instance, since I was not able to run scrapy without root permissions even after giving dbs and logs directory proper permissions. 

I am planning to do a fresh install for scrapy and scrapyd and see if I run into any problem again without root permission.

**Comment by jatinder85** [comment]
So I resolved my issue by downgrading the scrapy to v0.24 and it works great with scrapyd (1.0). Seems like scrapy v1.0 is incompatible with scrapyd v1.0 as pointed out in #100 issue.

**Comment by Digenis** [comment]
No, #100 is not concluded yet.
I think this issue is still valid.
If scrapy1 is incompatible then maybe we should answer "why".

**Comment by lepture** [comment]
How can I know the error stack in "Unhandled error in Deferred"?

**Comment by Digenis** [comment]
@jatinder85 you can still provide helpful feedback in this
if you are willing to upgrade scrapy to 1.0 and deploy your project.
Then all you'd have to do is schedule your spider once
and then once more, appending this argument to the curl command:
`-d setting=LOG_STDOUT=1`.
The log from the second job (with the LOG_STDOUT setting) should reveal the full error.

**Comment by Digenis** [comment]
The missing traceback is related to https://github.com/scrapy/scrapy/pull/2450
and can be solved by upgrading twisted.

I'm closing this issue because of insufficient info.

**Comment by kxxoling** [comment]
@Digenis ``system scrapyd start`` no longer works now? I'm using scrapyd 1.2.0 on Ubuntu 16.10.

**Comment by Digenis** [comment]
@kxxoling, this doesn't seem related to this ticket
(unless you log looks like https://github.com/scrapy/scrapyd/issues/110#issue-108523716)
there're other tickets about systemd

**Comment by kxxoling** [comment]
@Digenis I mean ``service scrapyd start``. On my machine, ``service scrapyd start`` returns ``Failed to start scrapyd.service: Unit scrapyd.service not found.``
