### ISSUE TITLE
The tgz file on pypi is not new enongh

### ISSUE THREAD

**Issue by crazygit** [scrapy/scrapyd#116]
I found that the code on https://pypi.python.org/pypi/scrapyd/1.1.0 is not as same as the master branch, No class DaemonStatus in it, Would you deploy it again.
```bash
$ curl http://localhost:6800/daemonstatus.json

<html>
  <head><title>404 - No Such Resource</title></head>
  <body>
    <h1>No Such Resource</h1>
    <p>No such child resource.</p>
  </body>
</html>
```

**Comment by crazygit** [comment]
Sorry, I found `DaemonStatus` does not release in 1.1.0

**Comment by Digenis** [comment]
Exactly, there is still development in the master branch that is not released.
You probably saw `DaemonStatus` in readthedocs that also shows the development branch, besides stable.
See #115

**Comment by crazygit** [comment]
yes, thank you!
