### ISSUE TITLE
Persist job data in Scrapyd

### ISSUE THREAD

**Issue by pablohoffman** [scrapy/scrapyd#12]
Job data in scrapyd is only kept in memory and thus removed when Scrapyd is restarted. We should store job data (in a sqlite or something) so that it persists after restarts. This is particularly important for completed jobs.

**Comment by dtheodor** [comment]
:+1:

**Comment by dtheodor** [comment]
Need pointers to which part of the code to look at for the in-memory objects we want to persist, where they are being retrieved and modified.

**Comment by Digenis** [comment]
I would look at the poller and the runner.
This non-trivial update can flow more smoothly if it's optional at first.
E.g. in scrapyd's configuration one may specify a class that handles persistent storage.
(The runner is already set by the configuration, the poller indirectly from the app)
When it's optional+configurabe like this, one can contribute his own class,
e.g. for another database backend
for others to appreciate, use, crash, debug, patch, contribute back.

**Comment by lepture** [comment]
Why not use redis?

**Comment by my8100** [comment]
Alternatively, you can use [ScrapydWeb v1.2.0](https://github.com/my8100/scrapydweb/blob/master/HISTORY.md) to persist jobs information in the database.

**Comment by imfht** [comment]
any update?

**Comment by mxdev88** [comment]
could someone take a look at the proposed PR #359? @Digenis ? Anyone else?

**Comment by mxdev88** [comment]
Hi maintainers (@dangra @Digenis @pablohoffman @redapple @scrapy),
Do you think PR #359 could be merged at some point? I've used it since and it's been working quite well but would like to move back to official release whenever possible.
Thanks!

**Comment by dsarmiento84** [comment]
Hi @mxdev88 I implemented PR #359 in my local scrapyd fork and it works well. Does it also have persistence on running jobs? Can it override the need of JOBDIR setting? I'll be great if it can keep track of running jobs and also if deamon is shutdown or restarted, it could pick them up from there. Thanks!

**Comment by mxdev88** [comment]
Hi @dsarmiento84, it persists only finished jobs. Running jobs are in a different queue. I think it would be quite challenging to implement persistence on running jobs as you would need to somehow save the state of your running job to to be able to restore on server restart.

**Comment by rpocase** [comment]
> ... you would need to somehow save the state of your running job to to be able to restore on server restart.

Could you hook into scrapy's built in JOBDIR functionality to persist these items? I would expect to need to effectively handle the below cases. The quite challenging portion could certainly be hiding in the details of hooking into this, but it at least seems like there should be a way to do so via scrapyd.

* Implement an interface for watching a `JOBDIR` to persist everything listed [here](https://docs.scrapy.org/en/0.22/topics/jobs.html#jobs-pausing-and-resuming-crawls)
* If a job is interrupted, load state based on everything captured in the `JOBDIR` equivalent

**Comment by rpocase** [comment]
> Could you hook into scrapy's built in JOBDIR functionality to persist these items? 

Doing a bit more digging here, it seems there are some very core scrapy problems (https://github.com/scrapy/scrapy/issues/4106) that would make even this miss a significant amount of data. To get a complete solution here, I would suspect upstream changes would be required.
