### ISSUE TITLE
Build eggs in test env

### ISSUE THREAD

**Issue by Digenis** [scrapy/scrapyd#124]
There are 2 binary eggs in master, containing pyc files.
Besides making reviewing harder (need to decompile)
I'd expect them to bug us when testing in different pythons
(the old egg is for py2.6).

Maybe tests should build the eggs.
This can prevent/complicate testing with eggs from different pythons
so we should decide whether such compatibility is a target.

**Comment by Digenis** [comment]
The eggs are for scrapy<1.0 and don't work with scrapy-1.6.

**Comment by my8100** [comment]
@Digenis 
Did you say eggs in https://github.com/scrapy/scrapyd/tree/master/scrapyd/tests ?
I found both py and pyc files in eggs.
And what about testing different eggs according to the Python version.

**Comment by Digenis** [comment]
egg compatibility across different pythons is not our problem to solve.
pkg_resources handles this.

This ticket is about replacing the binary eggs in the tests/ folder
with scrapy projects that will be built to eggs during testing, in the test env.

**Comment by atranou** [comment]
Hello! I am interested in this issue! Is it still open?

**Comment by jpmckinney** [comment]
@atranou It is open. Thanks for your interest!

**Comment by jpmckinney** [comment]
These egg fixtures have not been an issue. If they become an issue, we can re-open.
