### ISSUE TITLE
command `scrapyd` fails on Amazon Linux

### ISSUE THREAD

**Issue by aymericbouzy** [scrapy/scrapyd#127]
After successfully installing scrapyd with command `$ sudo /usr/local/bin/pip install scrapyd` on Amazon Linux AMI release 2015.09, I ran `$ scrapyd` and got

```
Traceback (most recent call last):
  File "/usr/local/bin/scrapyd", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 616, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 629, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 812, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pyasn1 0.1.7 (/usr/lib/python2.7/dist-packages), Requirement.parse('pyasn1>=0.1.8'), set(['pyasn1-modules', 'cryptography']))
```

**Comment by Digenis** [comment]
@aymericbouzy, are you familiar with [installing python packages](https://python-packaging-user-guide.readthedocs.org/en/latest/installing/)?
My guess is that you messed your setup while trying to install python2.7 on amazon linux.

Paste here the output of the following commands:
```sh
for python in `which -a python`; do echo $python; $python --version; echo ; done
for pip in `which -a pip`; do echo $pip; $pip list; echo; done
```

**Comment by aymericbouzy** [comment]
`[ec2-user@ip-172-31-19-155 ~]$ for python in `which -a python`; do echo $python; $python --version; echo ; done
/usr/bin/python
Python 2.7.10

[ec2-user@ip-172-31-19-155 ~]$ for pip in `which -a pip`; do echo $pip; $pip list; echo; done
/usr/local/bin/pip
attrs (15.2.0)
aws-cfn-bootstrap (1.4)
awscli (1.10.1)
Babel (0.9.4)
backports.ssl-match-hostname (3.4.0.2)
boto (2.39.0)
botocore (1.3.23)
cffi (1.5.2)
chardet (2.0.1)
cloud-init (0.7.6)
colorama (0.2.5)
configobj (4.7.2)
cryptography (1.2.2)
cssselect (0.9.1)
docutils (0.11)
ecdsa (0.11)
enum34 (1.1.2)
idna (2.0)
iniparse (0.3.1)
ipaddress (1.0.16)
Jinja2 (2.7.2)
jmespath (0.7.1)
jsonpatch (1.2)
jsonpointer (1.0)
kitchen (1.1.1)
lockfile (0.8)
lxml (3.5.0)
MarkupSafe (0.11)
mysql-connector-python (2.1.3)
MySQL-python (1.2.5)
paramiko (1.15.1)
PIL (1.1.6)
pip (8.0.2)
ply (3.4)
pyasn1 (0.1.7)
pyasn1-modules (0.0.8)
pycparser (2.14)
pycrypto (2.6.1)
pycurl (7.19.0)
pygpgme (0.3)
pyliblzma (0.5.3)
pyOpenSSL (0.15.1)
pystache (0.5.3)
python-daemon (1.5.2)
python-dateutil (2.1)
pyxattr (0.5.0)
PyYAML (3.10)
queuelib (1.4.2)
requests (1.2.3)
rsa (3.3)
Scrapy (1.0.5)
scrapyd (1.1.0)
service-identity (16.0.0)
setuptools (12.2)
simplejson (3.6.5)
six (1.8.0)
Twisted (15.5.0)
urlgrabber (3.9.1)
urllib3 (1.8.2)
virtualenv (12.0.7)
w3lib (1.13.0)
yum-metadata-parser (1.1.4)
zope.interface (4.1.3)

/usr/bin/pip
Traceback (most recent call last):
  File "/usr/bin/pip", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3020, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 616, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 629, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 807, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: pip==6.1.1`

I do have a problem with `pip` ...

**Comment by aymericbouzy** [comment]
I hadn't updated `setuptools` correctly. Sorry to have bothered you.
