### ISSUE TITLE
Start Scrapyd as service

### ISSUE THREAD

**Issue by ricoxor** [scrapy/scrapyd#132]
1. I would like to start scrapyd as service but when I start `scrapyd`,
    if I close the SSH session the service scrapyd close automatically.

 2. When I try to start as service like this I have an error :
    
        root@vps:~# service scrapyd start
        scrapyd: Failed to start scrapyd.service: Unit scrapyd.service failed to load: No such file or directory.

 3. And when i try to start `daemon scrapyd` the CURL request return :
    
        {"status": "error", "message": "Use \"scrapy\" to see available commands", "node_name": "vps"}

Can someone help me to start my scrapyd as service please !

**Comment by Digenis** [comment]
2. scrapyd doesn't support systemd
3. which curl request? what's is written in the scrapyd log?

**Comment by ricoxor** [comment]
I use `curl http://myip:6800/schedule.json -d project=default -d spider=expired`
Where can I find the logs on Ubuntu ?

**Comment by Digenis** [comment]
On your ubuntu I'd guess you could only start scrapy with the command it self.
Look for a file called logs in the directory where you started scrapy.

**Comment by ricoxor** [comment]
> On your ubuntu I'd guess you could only start scrapy with the command it self.
There is no possibility to start scrapy as service without keep le SSH window open ??

I can't find any errors log.

**Comment by Digenis** [comment]
No, it's not the job of ssh to do this. Look into software like tmux or screen.

Does scrapyd output something when you run the curl command?

**Comment by ricoxor** [comment]
What is the Goal of Scrapyd if we can't use it on a distant server ?
Scrapyd work fini when I start the command but I tried to start it as service with `daemon scrapy`
When I send the CURL command I have this return : 
`{"status": "error", "message": "Use \"scrapy\" to see available commands", "node_name": "vps"}`

When I start scrapyd without daemon everything work but I need to keep the ssh alive : 
`Process started:  project='default' spider='expired' job='c5874596e6c711e584be///home/CrawlerNDD/items/default/expired/c5874596e6c711e584befa163ea1e54c.jl'`

**Comment by Digenis** [comment]
The daemon command is just some software,
there may be multiple implementations matching its description.
scrapyd may or may not be compatible with some of them if any at all.

I suggest you read your system's documentation for the daemon command.
There you should find information like how to configure logging.
The daemon command should be able (I guess) to redirect the log to some file.
Share it here and we can see why scrapyd is incompatible with the daemon command.

**Comment by ricoxor** [comment]
Thank's Digenis I find the solution :
`daemon --chdir=/home/Crawler scrapyd`

I need to set the `--chdir` to load the service on the Scrapy folder !

**Comment by rangeonnicolas** [comment]
Hello!
> I need to set the --chdir to load the service on the Scrapy folder !

What is the default scrapy folder?
How to make sure that `daemon --chdir=/home/Crawler scrapyd` worked well? Because I tried with several directories as for `--chdir` but I don't know which one is the right one as I don't know how to check if this works

**Comment by Digenis** [comment]
There's no default,
just the current working directory from where you run scrapyd.

You say you want to check whether it works,
how about trying using it to check if if it works?

**Comment by jimatmv** [comment]
How about running this on system startup as a cron job?  Is there a way to use the "daemon --chdir=/home/Crawler scrapyd" command from ricoxor's post above in a cron bash script that's triggered on system startup? I've got that script working great in a terminal window. But it doesn't seem to work on system startup as a cron job.

With Ubuntu 16.04 the startup mechanisms have changed from init or upstart to systemd. That seems to have changed how scrapyd can be started as a daemon at system startup. Besides a cron job on startup, it looks like the only other way to do this is via a scrapyd.service systemd unit file, which I haven't got to work yet either.

**Comment by veronica-severyn** [comment]
jimatmv, Can you please give instructions on how you made it work on Ubuntu 16.04?

**Comment by jimatmv** [comment]
Sorry for my slow reply here.
Below are my complete notes on what I did.
Jim
=======

The trick to getting the boot-up cron job to run correctly is in setting up the environment for the script to be run by cron.  Cron does not have much of an environment setup when it runs, and initially when I tried this I kept getting errors of missing libraries on which scrapy or scrapyd were dependent. So I was able to write out the environment for both, i.e. when the script ran via a terminal and when it ran as a cron job (just Google techniques to get and record the environment from within a shell scrip).  Then I just added what was needed (namely the HOME variable) to set the environment correctly. The whole script is included below. In adding scrapyd to a new system, this script needs to be added to /home/<user>/cronjobs/scrapyd. The <user> needs to be adjusted accordingly for the system. Then the cron command is simply “/home/<user>/cronjobs/scrapyd/scrapyd-cron-bootstartup”, scheduled on system boot-up.

#!/bin/bash
# Script to run Scrapyd from a cron job on startup.
# Setup the correct environment for Scrapyd to run.
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
PWD=/usr/local/bin
HOME=/home/<user>
#Run scrapyd.
daemon --chdir=/usr/local/bin scrapyd

One other trick to this is the ‘daemon’ command, which doesn’t look to come as a standard part of Ubuntu 16.04.  This can be installed with the following command.
$ sudo apt install daemon

**Comment by Digenis** [comment]
twistd can also daemonize scrapyd
it's just that the default console script doesn't.
It also need some additional arguments for the working directory,
path to pid file and logging.

For systemd, see twisted's latest doc:
http://twistedmatrix.com/documents/current/core/howto/systemd.html
There's a ticket for scrapyd on systemd: #217
