### ISSUE TITLE
Cancel Problem

### ISSUE THREAD

**Issue by westwind027** [scrapy/scrapyd#154]
I found when I use  apscheduler  to execute cancel job  with requests  on the same machine with scrapyd, I can receive scrapyd response  successful ,but cannot cancel the job. With curl  or  postman there is  no problem.Finally  I add a argument "signal":"TERM" to the cancel.json, it's  just  ok,  very  queer !

**Comment by Digenis** [comment]
How long do you wait after posting to the webservice?
Once scrapy receives SIGINT it doesn't terminated immediately.
It first waits for any items/request yielded so far to finish processing.
If it receives a second SIGINT, it doesn't even wait for them and terminates.
Have you tried cancel.json twice in a row?

**Comment by westwind027** [comment]
When I use postman or curl to test cancel.json, I check the result with  listjobs.json  the task  is cancel immediately. But when I use python script ,when I receice the result , I check the result with listjobs.json , it still works,when wait for ten seconds , It still works.  

I haven't try to use cancel.json twice , I try use the signal parameter , then it's  OK

**Comment by Digenis** [comment]
Then it's not a bug.
You may be doing something wrong in your python script
since it works with curl.

**Comment by Rafalonso** [comment]
Can you share the code you used in your python script? I tested it and everything worked as expected.

**Comment by Rafalonso** [comment]
#181 fixes this problem

**Comment by netcaf** [comment]
Hello,
If we set DOWNLOAD_DELAY for a list of url,
It may wait too long to terminate the job for the first cancel.
Can we improve it? 
For example, wake up the sleeping spider(DOWNLOAD_DELAY) and let it respond to cancel operation.

**Comment by Digenis** [comment]
@netcaf, scrapy shouldn't initiate any new downloads after the 1st sigint.
If it keeps waiting to fulfil the download delay, it must be a bug.
If you can prove it (provide steps to reproduce the problem)
you should directly open an issue in scrapy (with steps to reproduce included).

@westwind027, @netcaf, have you tried the same without scrapyd?
Running the spider in the shell with scrapy and hitting ctrl-c just once?

**Comment by netcaf** [comment]
@Digenis, I have tried it without scrapyd, It still has the same issue. It exactly relates to scrapy.
sorry to confuse you.

**Comment by Digenis** [comment]
No problem, @netcaf, thanks for making it clear.
@westwind027, an answer from you is needed to proceed with the ticket

**Comment by hyahm** [comment]
my job more than 10 hours, can not stop  use curl  and have not log yet
```
http://localhost:6800/cancel.json -d project=default -d job=6487ec79947edab326d6db28a2d86511e8247444
```

**Comment by PandyYang** [comment]
my job more than 2 month, fail to stop it when i send cancel.json, it return status ok, but still running
`curl http://10.22.111.9:6800/cancel.json -d project=mitrejobs -d job=5beaaddaecdd11ec8b3b0002c94ec8aa`

**Comment by Digenis** [comment]
@hyahm @PandyYang the best you can do in this case is use gdb and attach to the scrapy process and see where it's stuck.
