### ISSUE TITLE
Fix race condition and potential error in logfile deleting

### ISSUE THREAD

**Issue by Digenis** [scrapy/scrapyd#159]
_This is a bit of a [WIP] issue because there are more details to be added when I have the time_

environ.py has the code responsible for deleting logfiles.

``` python
    def _get_file(self, message, dir, ext):
        logsdir = os.path.join(dir, message['_project'], \
            message['_spider'])
        if not os.path.exists(logsdir):
            os.makedirs(logsdir)
        to_delete = sorted((os.path.join(logsdir, x) for x in \
            os.listdir(logsdir)), key=os.path.getmtime)[:-self.jobs_to_keep]
        for x in to_delete:
            os.remove(x)
        return os.path.join(logsdir, "%s.%s" % (message['_job'], ext))
```

This deletes logs of hanged spiders.
When a spider hangs, it stops updating its log's mtime
and its log can be soon deleted by this code.
On windows, it should even crash because it doesn't allow open files to be deleted.

[psutil](https://pypi.python.org/pypi/psutil) can be used to check if the file is still open.
It is already being discussed as an optional dependency in scrapy (https://github.com/scrapy/scrapy/pull/1329)

There is also a race condition between `to_delete = sorted(...)` and `os.remove()`.
If something else removes the file, it will break. ENOENT should be ignored.

**Comment by jpmckinney** [comment]
Added commit to ignore any OSError, which includes the `to_delete` / `remove` race condition (FileNotFoundError / ENOENT).

For hanged spiders on Windows with open files, it'll just fail to delete those files. No need to deliberately check which files are open.
