### ISSUE TITLE
Can scrapyd pause and resume a job?

### ISSUE THREAD

**Issue by hieu-n** [scrapy/scrapyd#164]
`scrapy` can pause and resume a job with the `JOBDIR` setting. I tried to run my spider on `scrapyd` with the `JOBDIR` setting set, then terminate the `scrapyd` process. The `scrapyd` process stopped almost instantly after I pressed Ctrl-C. After I started `scrapyd` again, there were no jobs. I had to reschedule the job and started all over again.

**Comment by Digenis** [comment]
What you tried is not pausing and resuming a job but stopping scrapyd itself.
See #12. A patch for job persistence would be welcome.
