### ISSUE TITLE
Webdriver chrome error

### ISSUE THREAD

**Issue by jemjov** [scrapy/scrapyd#183]
when i use selenium webdriver chrome and scrapy in ubuntu first its work fine while using chromium as browser, but when i install google chrome at my desktop then it never work.
when i run the script it just open new window that google chrome do and not loading the page but terminal stopped working.

![aw](https://cloud.githubusercontent.com/assets/14123424/19473458/f85eba7a-9555-11e6-8eeb-73ebbabc3610.jpg)

anyone can help?

**Comment by Digenis** [comment]
Hi @jemjov,
We use github issues for reporting bugs and suggesting features.
For usage questions, try the mailing list:
https://groups.google.com/d/forum/scrapy-users
