### ISSUE TITLE
Can't run scrapyd

### ISSUE THREAD

**Issue by Miando** [scrapy/scrapyd#190]
`Traceback (most recent call last):
  File "/usr/local/bin/scrapyd", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: cryptography>=1.3.4
`
attrs==16.3.0
backports.ssl-match-hostname==3.5.0.1
cached-property==1.3.0
cffi==1.9.1
constantly==15.1.0
crypto==1.4.1
cryptography==1.6
cssselect==1.0.0
docker-compose==1.9.0
docker-py==1.10.6
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
enum34==1.1.6
functools32==3.2.3.post2
idna==2.1
incremental==16.10.1
ipaddress==1.0.17
jsonschema==2.5.1
lxml==3.6.4
Naked==0.1.31
ndg-httpsclient==0.4.2
parsel==1.1.0
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycparser==2.17
PyDispatcher==2.0.5
pyOpenSSL==16.2.0
PyYAML==3.12
queuelib==1.4.2
requests==2.11.1
Scrapy==1.2.2
scrapyd-client==1.0.1
service-identity==16.0.0
shellescape==3.4.1
six==1.10.0
texttable==0.8.7
Twisted==16.6.0
urllib3==1.19.1
virtualenv==15.1.0
w3lib==1.16.0
websocket-client==0.39.0
zope.interface==4.3.2

**Comment by Miando** [comment]
sudo  pip install --upgrade Scrapy 
was help

**Comment by Digenis** [comment]
@Miando, I see you are using scrapy-1.2 with scrapyd.
If you bump into any compatibility problems,
don't hesitate to report them here so that we'll fix them.

Also, how did you install scrapyd?
