### ISSUE TITLE
Overriding pipelines setting

### ISSUE THREAD

**Issue by PovilasKud** [scrapy/scrapyd#191]
When I try to override a simple variable setting (for example IMAGE_STORE) everything works fine but when I try to pass a 'ITEM_PIPELINES' setting it throws an error. 

```
2016-12-13T12:30:57+0200 [Launcher,10298/stderr] Usage
	=====
	  scrapy crawl [options] <spider>
	
	crawl: error: Invalid -s value, use -s NAME=VALUE
```

Code I use to schedule task:

```
ITEM_PIPELINES = {'zillow.pipelines.ZillowPipeline': 300,}
        settings = {'IMAGES_STORE': 'asdsad', 'ITEM_PIPELINES': ITEM_PIPELINES}
        scrapyd_id = scrapyd.schedule('zillow', 'zill', session_id=new_session.id, settings=settings)
```
OS: Ubuntu 16.04
Python: 2.7 

I'm using a scrapyd_api wrapper.

**Comment by Digenis** [comment]
@netcrime, although scrapyd may also need to be patched
this is mostly a scrapy issue.
See https://github.com/scrapy/scrapy/issues/2018
#61 is similar

**Comment by jpmckinney** [comment]
According to scrapy/scrapy#2018, this is fixed.
