### ISSUE TITLE
Scrapyd on Redhat

### ISSUE THREAD

**Issue by Kury25** [scrapy/scrapyd#200]
Env : 
- Redhat 7.3
- Python 2.7

With the last release, I have an error with the file utils/url.py, when I execute function 'url_has_any_extension'.
posixpath is not recognized:
```
return posixpath.splitext(parse_url(url).path)[1].lower() in extensions
	exceptions.NameError: global name 'posixpath' is not defined
```

To resolve it, I have to add a declaration on the top of this file (utils/urls.py) : 'import posixpath'

**Comment by Digenis** [comment]
Hi @Kury25,
Please include the full traceback in your issue
and the full paths of the files that you modify.
Scrapyd has no file named `url.py`
and the code you edit probably belongs to some other library.

**Comment by Kury25** [comment]
Sorry you're right. I read too fast the path. This issue is an issue for scrapy, not scrapyd.

**Comment by Digenis** [comment]
The scrapy developers would also appreciate it if you include the full trackback
and full paths in the issue you may be about to open in scrapy.

**Comment by Kury25** [comment]
I will be careful about it. Thanks

**Comment by redapple** [comment]
@Kury25 , you may be using an old Scrapy release.
That `import posixpath` was indeed missing in Scrapy 0.18 and below.
It was added from Scrapy 0.20 (https://github.com/scrapy/scrapy/blob/0.20/scrapy/utils/url.py) in https://github.com/scrapy/scrapy/pull/430
and has been in the code since. (Scrapy is now at 1.3.0)

**Comment by Kury25** [comment]
Yes I can see that. But in my project I have apparently to use this version. I'm making some tests to try a more recently version of scrapy. Thank you!
