### ISSUE TITLE
Pre-releases

### ISSUE THREAD

**Issue by Digenis** [scrapy/scrapyd#204]
We want to make an alpha release of 1.2.
In scrapy, a new release branch is created
and any subsequent PRs for master which are meant for the upcoming release
get merged to both master and the release branch.
(Can be messy when branching too early)

An alternative would be to bump all the pre-releases directly on master
because it's the branch where new development happens.
The amount of PR's with bugfixes is insignificant compared to PRs with features
so the amount of PR's that end up with conflicts because we change their merge base
to something other than the default is less if this default branch is a development branch.
Also, we don't have too many PRs meant for releases later than the upcoming one
so I don't mind keeping them as separate branches and resolving any merge conflicts later.
If they get complex, we can rebase them and merge them in a separate dev branch (eg 1.3dev)
and merge it to master after releasing 1.2.

In the second, more flat, scenario
we are ready to start bumping & tagging 1.2 alphas betas and RCs on master
until we get to gamma and create its dedicated branch.

**Comment by redapple** [comment]
I'm fine with releasing dcrapyd 1.2 alpha, beta and gamma from "master" branch.
This is what we currently do for scrapy these days.

**Comment by Digenis** [comment]
I bumped 1.2.0a1 and uploaded to pypi.
I'll soon write an announcement inviting testers.
