### ISSUE TITLE
Add schedule.json parameters to listjobs.json response

### ISSUE THREAD

**Issue by sieira** [scrapy/scrapyd#205]
Is there a way to retrieve the parameters of a scheduled task?

Currently
```sh
$ curl http://localhost:6800/schedule.json -d project=myproject -d spider=somespider -d setting=DOWNLOAD_DELAY=2 -d arg1=val1
```
Returns

```json
{"status": "ok",
 "pending": [{"id": "78391cc0fcaf11e1b0090800272a6d06", "spider": "somespider"}]
}
```

I wonder if there is a way to get:

```json
{"status": "ok",
 "pending": [{
    "id": "78391cc0fcaf11e1b0090800272a6d06",
    "spider": "somespider",
    "setting": {"DOWNLOAD_DELAY": 2},
    "arg1": "val1"
}]
}
```

**Comment by Digenis** [comment]
@sieira, no.
This information exists only for pending jobs.
I'd say scrapyd is far from providing this feature.
Also, I think we shouldn't provide an API for this
until we rewrite the webservice to accept parameters in a better format.

**Comment by my8100** [comment]
Try this https://github.com/my8100/scrapydweb , and you can get the schedule history from http://127.0.0.1:5000/schedule/history.log
 
![image](https://user-images.githubusercontent.com/37427675/47090132-d6585880-d254-11e8-80e0-e657f73c8b1a.png)

**Comment by jabadia** [comment]
Would you be willing to accept a patch with this enhancement?
* store the arguments in `ScrapyProcessProtocol()` (around https://github.com/scrapy/scrapyd/blob/4520c45acc115d0fc766eae30788468a77690433/scrapyd/launcher.py#L44)
* report the arguments in `listjobs.json` for pending, running and finished jobs

**Comment by jpmckinney** [comment]
Maybe related: #39

**Comment by jpmckinney** [comment]
> store the arguments in ScrapyProcessProtocol()

Noting that this was the approach in #254

**Comment by jpmckinney** [comment]
See also comments in PR #272

**Comment by jpmckinney** [comment]
Done. Args are collected into `args` instead of being free-floating.
