### ISSUE TITLE
can not stop/cancel jobs on scrapyd

### ISSUE THREAD

**Issue by monalisir** [scrapy/scrapyd#206]
I have read all issues there, but I do not find the answer to solve my problem. 
I create a scrapyd server on Ubuntu 14.04 LTS version, use nginx with basic authentication
and managed by supervisor.
Every thing is running ok. But some times, It will hang up and never end.
So I need to cancel the running job, It can be terminated by Ctrl+C running as a script on server or my local machine, But can not through scrapyd api even with signal INT or TERM. 
Scrapy (1.3.0)
scrapyd (1.1.1)
Twisted (16.6.0)

**Comment by Digenis** [comment]
@monalisir, when you try Ctrl+C out of scrapyd and it works
is the spider already hung?

See this comment https://github.com/scrapy/scrapyd/issues/75#issuecomment-219710925
Next time it hangs, please attach a debugger and check if it's the same problem.
The hanging can be a bug in scrapy.
