### ISSUE TITLE
Configurable log file name and format

### ISSUE THREAD

**Issue by OldPanda** [scrapy/scrapyd#207]
Currently the scrapy log file generated by scrapyd is named as [job's id](https://github.com/scrapy/scrapyd/blob/master/scrapyd/environ.py#L63) and format is hardcoded as [`.log`](https://github.com/scrapy/scrapyd/blob/master/scrapyd/environ.py#L35), similar case also happens on items file. It would be better if we could customize those file names and formats, like, if we wish to include spider's name or timestamp in a log name and compress it into `zip` format to save space.

**Comment by Digenis** [comment]
@OldPanda, here are 2 ways to do it.

The spider name is already used in the log path, it's the logfile's parent folder.
You pass the `jobid` argument to schedule.json.
This will work with the current stable release of scrapyd.
``curl http://server:port/schedule.json -d project=proj -d spider=spider -d jobid=`date +%s` ``
The log file will look like this `proj/spider/1485423127.log`
For compression, you can write a cronjob.
(FYI scrapyd also doesn't compress its own log, this is a job for logrotate)

Also see https://github.com/scrapy/scrapyd/pull/169
(back then, it didn't occur to me or anyone else that we can just pass a jobid)

Another way to do this is to write your own [environment](https://github.com/scrapy/scrapyd/blob/master/scrapyd/environ.py).
Currently, the environment class is not configurable
but I think we should make it configurable like most scrapyd's components.
You should then be able to use it in the next release.

Too complex solutions are unlikely to get into the upcoming 1.2
but we can discuss ideas.

**Comment by jpmckinney** [comment]
This feature request has not received additional interest. As described above, log file naming can be overridden, and log file compression can be the responsibility of tools like logrotate, instead of adding it to scrapyd.
