### ISSUE TITLE
Retrieve log files through REST API

### ISSUE THREAD

**Issue by engelkek** [scrapy/scrapyd#208]
I would like to be able to retrieve log files for finished jobs through the REST API. The basic UI provides a link to the log files, but the API does not offer the same.

**Comment by Digenis** [comment]
Hi, @engelkek,

The API gives you a way to choose a log filename.
This is done with the `LOG_FILE` setting when you schedule a spider run.
Any settings and spider arguments are lost after the spider is popped from the queue.

Currently it is only possible to retrieve the log files
of spiders that didn't get their log filenames overridden.
You can use the website directly for this,
it's just a GET request.

Currently, the documentation doesn't promise anything about it
but we don't plan to change the url path.
Even if we do, it will go through a deprecation circle with a warning.

It does make sense to be able to retrieve the log files even when the setting gets overridden
but this means that we'll have to start storing such settings even after the spider starts.
This needs some redesign. We are open for ideas.

**Comment by jpmckinney** [comment]
As described above, the log file URLs (which by default use the job ID, retrieved from other API endpints) are essentially an API already.
