### ISSUE TITLE
Passing configurations parameters to scrapyd from command line during running scrapyd service

### ISSUE THREAD

**Issue by jxltom** [scrapy/scrapyd#210]
Well, an enhancement where configuration parameters can be passed to scrapyd from command line, e.g. ```scrapyd --max_proc_per_cpu=10```, during running scrapyd service will be great. Though it is not urgent, it is quite common and convenient for letting users doing so.

**Comment by jpmckinney** [comment]
I will mark this as wontfix, as it seems sufficient to change the configuration file and restart the service, and there has been no other participation or requests for this issue.
