### ISSUE TITLE
Please change jobid from uuid1 to uuid4

### ISSUE THREAD

**Issue by drozzy** [scrapy/scrapyd#214]
I'm using job id as part of a business process and uuid1 is not sufficient
https://github.com/scrapy/scrapyd/blob/1c0d81d3151fa7c403fa0fae50b92150a8af95f9/scrapyd/webservice.py

Is there any reason not to use uuid4?

**Comment by hosseinmousavi** [comment]
why `uuid1` is not sufficient? `uuid1` uniqueness is same as `uuid4` uniqueness, as i know just for revealing MAC address it's preferable to use `uui4`

**Comment by drozzy** [comment]
Basically, just a greater chance of collision: "This means you are guaranteed to get a completely unique ID, unless you generate it from the same computer, and at the exact same time. In that case, the chance of collision changes from impossible to very very small because of the random bits."

https://www.sohamkamani.com/blog/2016/10/05/uuid1-vs-uuid4/

Now, I've created this issue LOONG time ago, so I actually don't remember what my exact problem with it was. I say feel free to close it, and if someone has a problem with it, re-open it again.
