### ISSUE TITLE
I got this error when schedule a spider with curl

### ISSUE THREAD

**Issue by xcf007** [scrapy/scrapyd#219]
**curl.exe http://localhost:6800/schedule.json -d project=default -d spider=details**
{"status": "error", "message": "Use \"scrapy\" to see available commands", "node
_name": "01A710601439615"}

New to scrapyd,Thanks!

**Comment by xcf007** [comment]
py2.7 x86 + scrapyd 1.1

**Comment by Digenis** [comment]
Hi @xcf007,
scrapyd doesn't officially support windows
but let's look into the issue.
It'd be nice to al least have experimental support in the next release.

Try installing the latest alpha version of scrapyd, scrapyd-1.2.0a1.
The new version should contain a full traceback in the webservice's response
and we'll get a clue why it doesn't work.

**Comment by Digenis** [comment]
@xcf007 did you have any luck with scrapyd-1.2?
