### ISSUE TITLE
Can API support PID？

### ISSUE THREAD

**Issue by homchou** [scrapy/scrapyd#222]
see title

**Comment by Digenis** [comment]
You mean that listjobs.json should list the PID just like the site does?
Yes. This could be used in scripts
and scrapyd should have not reason to hide it.

Since this is trivial, I shall commit a patch directly to the master branch
unless some other member wants to discuss it first.

**Comment by Digenis** [comment]
@homchou, would you like to open a PR?

**Comment by Digenis** [comment]
@homchou, never mind, I created #223
