### ISSUE TITLE
where is the log of scrapyd itself?

### ISSUE THREAD

**Issue by abinbao** [scrapy/scrapyd#232]
when I canceled my spider,the scrapyd display like this,I don't know what's with it

`2017-05-18T18:58:57-0700 [-] Timing out client: IPv4Address(TCP, '192.168.17.3', 58609)`

**Comment by Digenis** [comment]
@okbeng1302,
this is probably irrelevant to scrapyd.
My guess is that it's twisted timing out the browser's connection
which probably used the keep-alive mechanism.
It's not a bug but I'd prefer it if twisted log this in debug log level.
I don't think we can do anything about it
except not supporting keep-alive.

Do you have any problems cancelling jobs?

**Comment by hosseinmousavi** [comment]
You can pass --logfile argument to specify log file
`scrapyd --logfile=scrapyd.log`
have in mind that you can't choose log level because scrapyd use twisted log.msg for logging
see launcher.py in scrapyd files

**Comment by jpmckinney** [comment]
The issue title is "where is the log of scrapyd itself?" which has been answered.
