### ISSUE TITLE
Scapyd raise NotADirectoryError from .egg file

### ISSUE THREAD

**Issue by amarynets** [scrapy/scrapyd#241]
I added some text file to my project and when I run scrapyd server from the same folder as my project - all work fine. But If I run scrapyd from supervisor and sending a request for crawling - I'm getting error
```
File "/tmp/exa-1504178736-lyojtcmr.egg/exa/pipelines.py", line 29, in __init__
  File "/tmp/exa-1504178736-lyojtcmr.egg/exa/classificator/news_classify_tag.py", line 29, in __init__
NotADirectoryError: [Errno 20] Not a directory: '/tmp/exa-1504178736-lyojtcmr.egg/exa/classificator/large.txt'
```
My `setup.py` file looks like this
```
from setuptools import setup, find_packages

setup(
    name='project',
    version='1.0',
    packages=find_packages() + ['exa'],
    entry_points={'scrapy': ['settings = exa.settings']},
    package_dir={'exa': 'exa'},
    package_data={'exa': ['classificator/large.txt']}
)
```
Why am I getting this error when scrapyd works as a daemon?

**Comment by amarynets** [comment]
I fixed this issues, you should use pkg_resources.resource_stream(resource_package, resource_path)

**Comment by Digenis** [comment]
Marked as a bug because it should have been in the docs.

**Comment by Digenis** [comment]
See also:
https://github.com/scrapy/scrapyd-client/issues/46

**Comment by amarynets** [comment]
@Digenis Where should it be in the docs?

**Comment by Digenis** [comment]
@amarynets,

If we accept that it should be in the scrapyd doc
(the other place would be scrapyd-client)
then it should be written in the "deploy" topic.

Would you like to open a PR?

**Comment by amarynets** [comment]
@Digenis yes, I will do it

**Comment by jpmckinney** [comment]
Please see the new docs at https://github.com/scrapy/scrapyd-client#including-static-files and https://github.com/scrapy/scrapyd-client#egg-caveats
