### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by liangWenPeng** [scrapy/scrapyd#243]
Hey，I install scrapyd on ubuntu14 using python 2.6. When I launch scrapyd，the site can only be accessed locally . But when I launch a  SimpleHTTPServer on 6800 , I can visit the SimpleHTTPServer  remotely. How can I solve or debug this problem? thx

**Comment by FangXing** [comment]
The default bind_address is 127.0.0.1,You should set this option with 0.0.0.0 in your own config file
