### ISSUE TITLE
Twisted python failure Failure class OpenSSL.SSL.Error

### ISSUE THREAD

**Issue by affemann2** [scrapy/scrapyd#247]
I am new to scrapyd. I am trying to scrape the following sitemap. 

https://www.mdcalc.com/sitemap.xml

Here is my spider

    from scrapy.contrib.spiders import SitemapSpider
    from skitter.items import SkitterItem

    class MdcalcSpider(SitemapSpider):
        name = 'mdcalc'
        sitemap_urls = ['https://www.mdcalc.com/sitemap.xml']
        sitemap_rules = [('.*', 'parse')]    

        def parse(self, response):
            item = SkitterItem()
            item['url'] = response.url
            item['title'] = ''.join(response.xpath('//h1//text()').extract())
            item['content'] = ' | '.join(filter(None, (x.strip() for x in 
            response.xpath('//h1//text()').extract())))
            yield item

When I run

    scrapy crawl mdcalc

It works perfectly

However when I try to deploy scrapyd-deploy local using the following command

    curl localhost:6800/schedule.json -d project=skitter -d spider=mdcalc

I get the following Error

    2017-09-30 23:25:34+0000 [mdcalc] INFO: Crawled 0 pages (at 0 pages/min), 
    scraped 0 items (at 0 items/min)
    2017-09-30 23:25:34+0000 [scrapy] DEBUG: Telnet console listening on 
    127.0.0.1:6023
    2017-09-30 23:25:34+0000 [scrapy] DEBUG: Web service listening on 
    127.0.0.1:6080
    2017-09-30 23:25:34+0000 [mdcalc] DEBUG: Retrying <GET 
    https://www.mdcalc.com/robots.txt> (failed 1 times): 
    [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]
    2017-09-30 23:25:36+0000 [mdcalc] DEBUG: Retrying <GET 
    https://www.mdcalc.com/sitemap.xml> (failed 1 times): 
    [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]
    2017-09-30 23:25:39+0000 [mdcalc] DEBUG: Retrying <GET 
    https://www.mdcalc.com/robots.txt> (failed 2 times): 
    [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]
    2017-09-30 23:25:42+0000 [mdcalc] DEBUG: Retrying <GET 
    https://www.mdcalc.com/sitemap.xml> (failed 2 times): 
    [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]
    2017-09-30 23:25:45+0000 [mdcalc] DEBUG: Gave up retrying <GET 
    https://www.mdcalc.com/robots.txt> (failed 3 times): 
    [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]
    2017-09-30 23:25:45+0000 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] 
    ERROR: Unhandled error in Deferred:
    2017-09-30 23:25:45+0000 [HTTP11ClientProtocol (TLSMemoryBIOProtocol),client] 
    Unhandled Error
	    Traceback (most recent call last):
	    Failure: twisted.web._newclient.ResponseNeverReceived: 
        [<twisted.python.failure.Failure <class 'OpenSSL.SSL.Error'>>]

It seems like it works locally but when I try to deploy using scrapyd it returns the error. Do I need to add something to my settings.py file? Or is there a way to run my curl command to make it work. Thanks for your help.

**Comment by samueltc** [comment]
Are you using an old version of Scrapy? I had the exact same problem, just upgraded to Scrapy 1.4.0 (python2, Twisted 17.9.0, cryptography 2.1.3) and it fixed this issue.

**Comment by Digenis** [comment]
@affemann2,
We need the pip freeze output for the scrapyd environment.

**Comment by s-pace** [comment]
👋 
Might be related to [this FAQ](https://docs.scrapy.org/en/latest/topics/settings.html#downloader-client-tls-method)

The website you want to scrap use SSL instead of the classic TLS one.

[REF](https://github.com/scrapy/scrapy/issues/1429)

**Comment by Digenis** [comment]
not a scrapyd issue
