### ISSUE TITLE
Scrapyd : Installation is not creating config and log files or directory

### ISSUE THREAD

**Issue by Samarpitr** [scrapy/scrapyd#249]
I installed scrapyd on ubuntu 16.04 using pip install scrapyd but unfortunately this process not creating any file or folder in /etc or /var dir as expounded in scrpayd documentation.

**Comment by Digenis** [comment]
Hi, @Samarpitr,
the documentation you red is about the debian package of scrapyd.
scrapyd, the a python package, doesn't create any such directories.
However, you can read the install script and get an idea of what it does,
which users it created, which directories with what permissions etc.

**Comment by sreeshk692** [comment]
Can you please give the steps after installing scrapyd using pip install

**Comment by Samarpitr** [comment]
Thanks @Digenis
