### ISSUE TITLE
Officially deprecate Ubuntu packages from archive.scrapy.org

### ISSUE THREAD

**Issue by boogheta** [scrapy/scrapyd#252]
Hello,
It seems like the packages source server is not up anymore, resulting in apt updates errors.
Is this a temporary issue or has the server been completely given up? If the latter, it would be good to update scrapyd's public doc as it recommends to install using this repository source.

**Comment by amin24e** [comment]
i'm facing the same problem

**Comment by Digenis** [comment]
Cc: @redapple

**Comment by redapple** [comment]
You can consider archive.scrapy.org as deprecated. I don't forsee it getting up again in the future.

**Comment by boogheta** [comment]
Can you update the public documentation then?
It leads to "apt-get update" errors for users who did use it and it is really misleading letting people think there exists actual package to install the daemon when there aren't anymore :/

**Comment by redapple** [comment]
Right @boogheta . I've renamed the issue here.

**Comment by Digenis** [comment]
From what I read, there's no deprecation.
The mirror is down permanently
so we'd rather remove it from the doc.

**Comment by Jazzity** [comment]
So um, as someone new to all this, what does this mean? Should we just ignore the paragraph "Installing Scrapyd in Ubuntu" and just go for "pip install scrapyd"?

**Comment by Digenis** [comment]
@Jazzity, yes, the paragraph about installing scrapyd in ubuntu should be ignored.
There are no longer instructions for a system install of scrapyd.
However, reading the install scripts for ubuntu can help you figure out how to do a system install.
We need documentation on this. PRs are welcome.

**Comment by Digenis** [comment]
resolved in 60039c76270c7020062bd41919fe0631846db1ca

the should be a separate ticket for adding install documentation
