### ISSUE TITLE
scapyd-deploy

### ISSUE THREAD

**Issue by ghostAD** [scrapy/scrapyd#255]
scapyd-deploy 
urlopen error [Errno 99] Cannot assign requested address

```
root@root:~# scrapyd-deploy
Packing version 1508754132
Deploying to project "spider-proxy" in http://localhost:6800/addversion.json
Deploy failed: <urlopen error [Errno 99] Cannot assign requested address>


root@root:~# netstat -anp|grep 6800
root@root:~# 
```

**Comment by Digenis** [comment]
@ghostAD, you don't have scrapyd running (or it's on a different port).
You need to run it before you can deploy.

Feel free to reopen this issue if it doesn't resolve after running scrapyd.
