### ISSUE TITLE
scrapyd no longer provides an easy way to do a system install

### ISSUE THREAD

**Issue by Digenis** [scrapy/scrapyd#258]
Even before the ubuntu packages got deprecated (#252)
the scrapyd builds for ubuntu/debian where quite unusable.

We should have instructions on how to do a system install.
The current steps, as seen in the debian/ folder
are as follows:
- create scrapyd's directories,
seen in https://github.com/scrapy/scrapyd/blob/1.2/debian/scrapyd.dirs
- create a system user account and give it rights to the directories
as seen in https://github.com/scrapy/scrapyd/blob/1.2/debian/scrapyd.postinst
- add an init script for your system,
based on https://github.com/scrapy/scrapyd/blob/1.2/debian/scrapyd.init
- create a python environment for the scrapyd user
and install scrapyd and its dependencies in it.
- make sure the init script runs scrapyd using this environment
(This is the only part I haven't yet tried)

To a seasoned sysadmin, it's a matter of minutes.
The fancy part is to set up a python environment
to be used by the scrapyd user and its init script.
This is necessary as scrapyd may not agree
with the packages or package versions
used by the system python.
(also, not all required python packages may be system packages)

**Comment by jpmckinney** [comment]
There is nothing very special about making it a system service. For example, most of the following is already documented:

1. Create a user to run Scrapyd
1. Create the [configuration file](https://scrapyd.readthedocs.io/en/stable/config.html#configuration-file) in the user's home directory
1. Create any directories mentioned in the configuration file (eggs, dbs, logs), owned by that user
1. Install Scrapyd in a virtual environment in the user's home directory
1. Create `/etc/systemd/system/scrapyd.service`, if you like to use `systemd`

It can look like:

```
[Unit]
Description=Scrapyd
After=network.target

[Service]
User=myuser
Group=mygroup
UMask=2002
# Add any environment variables you want.
Environment="key=value"
WorkingDirectory=/home/scrapyd/scrapyd
ExecStart=/home/scrapyd/scrapyd/.ve/bin/scrapyd --nodaemon --logfile=/var/log/scrapyd/scrapyd.log
LimitNOFILE=512000

[Install]
WantedBy=multi-user.target
```
