### ISSUE TITLE
improve "scheduled jobs" listing page

### ISSUE THREAD

**Issue by michaelnguyen2021** [scrapy/scrapyd#26]
localhost:6800/jobs page should have
- [x] start_time for each scheduled jobs
- [ ] pagination (25 jobs per page)
- [ ] display jobs by date range

**Comment by Digenis** [comment]
start_time added in #256

**Comment by jpmckinney** [comment]
I will mark this as wontfix, as the page is sufficient for basic needs, and other needs can be satisfied by creating a UI that uses the listjobs.json endpoint.
