### ISSUE TITLE
Read conf text files - Error File not Found 

### ISSUE THREAD

**Issue by aleroot** [scrapy/scrapyd#261]
I'm deploying an egg file to scrapyd that in the root contains two text configuration files lets say list1.txt and list2.txt, that I'm referencing from the settings.py with two lines like these :

CONF_FILE1 = 'list1.txt'
CONF_FILE2 = 'list2.txt'

The problem is that even though I've put the two files into the egg that I deploy, adding this configuration to the setup.py : 

    data_files   = [
            ('', [
                'list1.txt',
                'list2.txt',
                'scrapy.cfg'
            ]),
        ],

The application at the startup fails because the spider can't find those files (File Not found exception).

Everything is working fine calling the scrapy from the command line from the project root directory.

What is the default working directory of the scrapyd daemon ? Can I use a relative path ? Or should I use the absolute path ?

**Comment by brd6** [comment]
i have the same issue with dotenv files, someone have a solution?

**Comment by jpmckinney** [comment]
Please see the new docs at https://github.com/scrapy/scrapyd-client#including-static-files and https://github.com/scrapy/scrapyd-client#egg-caveats
