### ISSUE TITLE
Python3 JSON datatype issue

### ISSUE THREAD

**Issue by rafspiny** [scrapy/scrapyd#264]
I am having a problem using the `scrapyd-deploy` utility.
When I run `scrapyd-deploy -L local` to list all of my projects, I got:
```
Traceback (most recent call last):
  File "/usr/local/bin/scrapyd-deploy", line 292, in <module>
    main()
  File "/usr/local/bin/scrapyd-deploy", line 81, in main
    projects = json.loads(f.read())['projects']
  File "/usr/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

Apparently the solution would be to decode the input. So line 81 of scrapyd-deploy should become: 
```python
projects = json.loads(f.read().decode('utf-8'))['projects']
```
Am I the only one having this issue?

I am running Python 3.4 and this is the relevant output from pip:
```
$ pip list | grep -i scrapy

Scrapy (1.4.0)
scrapy-random-useragent (0.2)
scrapy-splash (0.7.2)
scrapyd (1.2.0)
scrapyd-client (1.1.0)
scrapyrt (0.10.0)
```

**Comment by Digenis** [comment]
This is an issue for https://github.com/scrapy/scrapyd-client
I think that we should decode from ascii,
since in json you can encode all strings using unicode escape sequences.

**Comment by rafspiny** [comment]
Sorry, silly me. I misplaced it.
Closing this one and moving it to the right repository.
