### ISSUE TITLE
scrapyd run a spider project, after a day, will be suspended

### ISSUE THREAD

**Issue by zparkgao** [scrapy/scrapyd#265]
when i run my spider-redis project a few hours later,  it will be _**# suspended**_ and can't deal any requests ,i don't know why? 
and when i use cancel.json to stop the task ,it returns: Received SIGTERM, shutting down gracefully. Send again to force 
who can help me to deal it, thanks!

**Comment by Digenis** [comment]
@zparkgao, does it have the same behaviour without scrapyd?

**Comment by jpmckinney** [comment]
No answer to clarifying question after many years, so closing.
