### ISSUE TITLE
max_proc_per_cpu not applied

### ISSUE THREAD

**Issue by yuseferi** [scrapy/scrapyd#266]
I have the following two scrapy project with the following configuration

```
[settings]
default = Project1.settings
[deploy]
url = http://localhost:6800/
project = Project1

[scrapyd]
eggs_dir    = eggs
logs_dir    = logs
logs_to_keep = 500
dbs_dir     = dbs
max_proc    = 5
max_proc_per_cpu = 10
http_port   = 6800
debug       = off
runner      = scrapyd.runner
application = scrapyd.app.application
```

and Project2

```
[settings]
default = Project2.settings
[deploy]
url = http://localhost:6800/
project = Project2

[scrapyd]
eggs_dir    = eggs
logs_dir    = logs
logs_to_keep = 500
dbs_dir     = dbs
max_proc    = 5
max_proc_per_cpu = 10
http_port   = 6800
debug       = off
runner      = scrapyd.runner
application = scrapyd.app.application
```
but when I take look at http://localhost:6800/jobs I always see just 8 item in running, it means default max_proc_per_cpu is applied,  I delete the projects 
`curl http://localhost:6800/delproject.json -d project=Project1` 

`curl http://localhost:6800/delproject.json -d project=Project2`

and deploy them again for make sure new changes deploy. but the running spiders number still is 8 .

I have 2 core of cpu I could get it with 
`python -c 'import multiprocessing; print(multiprocessing.cpu_count())'`.
where is the problem? 
Why it don't apply?

**Comment by Digenis** [comment]
Hi, @zhilevan,

Thank you for your detailed issue description.

scrapyd currently doesn't support per-project configurations
and this is what you seem to try to do.

scrapyd also doesn't accept configuration from projects.
This configuration file you are writing is only for scrapyd-client,
which need to know how and where to deploy.
See https://scrapyd.readthedocs.io/en/stable/config.html#configuration-file

**Comment by jpmckinney** [comment]
User support request has been answered. Scrapyd configuration needs to be configured where Scrapyd is running. Docs: https://scrapyd.readthedocs.io/en/stable/config.html
