### ISSUE TITLE
about "...6800:/listspiders.json?project="myproject_name"

### ISSUE THREAD

**Issue by chaseSpace** [scrapy/scrapyd#277]
I got an error output for this api in browser,and i have no idea now,help me plz
ERROR INFO:
{"status": "error", "message": "Scrapy 1.5.0 - no active project\\r\\n\\r\\nUnknown command: list\\r\\n\\r\\nUse \"scrapy\" to see available commands\\r\\n", "node_name": "ELI"}
but I do have a couple of projects in my virtuanenv's scrapy env（localhost）.
the other api are ok.

**Comment by hosseinmousavi** [comment]
check you have a `scrapy.cfg` in right location
