### ISSUE TITLE
Specific log file when launching a spider with scrapyd

### ISSUE THREAD

**Issue by m-vdb** [scrapy/scrapyd#28]
Hi there,

I'm currently launching my spiders with scrapyd, and I have some spiders that I can launch several times with distinct arguments (I call these ones generic spiders). The thing is, I want to have distinct log files according to those arguments, and I can't find anywhere any configuration to do that. So my first question is: is it possible to configure scrapyd to do so ?

Then I took a look at your code, and find out interesting lines where we could do that without being too intrusive, right [here](https://github.com/scrapy/scrapyd/blob/master/scrapyd/environ.py#L38-L39). It might be achieved by simply passing an optional log_file argument in messages. Do you think it could be possible ?

Thanks !

**Comment by sujaymansingh** [comment]
@m-vdb Did you find anything for this? I have a fork that might help:
https://github.com/EDITD/scrapyd/tree/editd-fixes

https://github.com/EDITD/scrapyd/commit/178623ed12a473c7dec63bc62eb8b541bf9d01f7

I also submitted a PR, but it looks like scrapyd is no longer being maintained :( What a pity! But let me know if the fork helps.

**Comment by m-vdb** [comment]
@sujaymansingh that's pretty cool! well we implemented an dirty kludgy in-house solution for that... :(

**Comment by jayzeng** [comment]
@m-vdb Thanks for the PR, I code reviewed, let me know what you think.

**Comment by m-vdb** [comment]
I didn't provide the PR, it's @sujaymansingh :)

**Comment by jayzeng** [comment]
Oops, my bad @m-vdb . @sujaymansingh please take a look at the PR :)
