### ISSUE TITLE
Can I pass more than one setting to `schedule.json` ?

### ISSUE THREAD

**Issue by wlh320** [scrapy/scrapyd#280]
Hello! Thanks for seeing this issue.

The doc of `schedule.json`says:
> setting (string, optional) - a Scrapy setting to use when running the spider

So can I pass two or more Scrapy settings to the spider?

For example, I can run the following command in command line:
```
scrapy crawl somespider -s JOBDIR='./jobs' -s CLOSESPIDER_TIMEOUT=100
```
Then it can pass both two settings to the job.

What should I do if I want to pass those two settings via API `schedule.json` ?

Thank you!

**Comment by wlh320** [comment]
I'm sorry, I suddenly realized that I can handle it. It's my fault. Sorry for troubling you!

**Comment by nadzimo** [comment]
Hi @wlh320 – can you please explain how you were able to pass settings through the schedule API?

**Comment by wlh320** [comment]
@nadzimo Hi! You can pass settings with any HTTP client like `requests` or `urllib`. I use `requests` in my project. The following code is for your reference.
```python
settings = [
    ('project', 'default'),
    ('spider', 'xxx'),
    ('setting', 'JOBDIR=%s' % jobdir),
    ('setting', 'CLOSESPIDER_TIMEOUT=%d' % duration)
]
res = requests.post('http://localhost:6800/schedule.json', data=settings)
res = res.json()
if res.get('status') == 'ok':
    pass
```
In the above code, I pass a **list of tuples** as POST data instead of **dict** to pass more than one setting to scrapyd API, or values with same key will be overridden.

**Comment by nadzimo** [comment]
Wonderful!

**Comment by Apuyuseng** [comment]
you can 
```python
import requests

data = {
      ...
      setting=["JOBDIR=%s"% jobdir, "CLOSESPIDER_TIMEOUT=%s"%timeout]
}
resp = requests.post(url,data=data)
```

by soure code add print ,this is able

**Comment by julosaure** [comment]
Thank you @Apuyuseng

**Comment by jpmckinney** [comment]
FYI, in Scrapy 1.6.0, by setting jobs_dir in the scrapyd.conf file, Scrapyd will automatically assign a unique JOBDIR to each crawl.
