### ISSUE TITLE
How to run scrapyd as a system service on a windows operating system

### ISSUE THREAD

**Issue by zamzus** [scrapy/scrapyd#285]

**Comment by Dashu-Xu** [comment]
hi, there has a small tool named `SrvanyUI`, this might be the way you are looking for.
but when i'm using this tool i find that if you using selenium in your project, somehow the browser(e.g. FireFox) can't lunch as it should be. 
hope this will work for you.

**Comment by jpmckinney** [comment]
I imagine it is the same as making any other software a system service on Windows. Please refer to the documentation of service managers for Windows.
