### ISSUE TITLE
Is project abandoned? 

### ISSUE THREAD

**Issue by VanDavv** [scrapy/scrapyd#288]
Hi

I want to ask whether this project is abandoned, and if yes, is someone from community has made a fork which will be in the future maintained?

Last commit is from January and I can see very little activity from contributors or owners

**Comment by pablohoffman** [comment]
Yes, Scrapyd hasn't had a maintainer for long while now. On 2014 there was an attempt to bring a new maintainer onboard (see #44) but it didn't prosper for long.

You may take a look at a new open source project called ScrapydWeb that was announced a couple weeks ago. I don't know how good it is, but it's getting some initial traction:
https://www.reddit.com/r/scrapy/comments/9okmcr/scrapydweb_fullfeatured_web_ui_for_monitoring_and/
https://github.com/my8100/scrapydweb

And if you don't mind hosting your spiders in a proprietary service, you have Scrapy Cloud: https://scrapinghub.com/scrapy-cloud

**Comment by pablohoffman** [comment]
Oh, I'm completely to that @VanDavv. But I haven't heard of any other volunteers recently.
