### ISSUE TITLE
twisted.web.error.UnsupportedMethod: Expected one of [b'HEAD', b'object', b'POST']

### ISSUE THREAD

**Issue by yanbyang** [scrapy/scrapyd#289]
```
2018-05-31T20:26:16+0800 [_GenericHTTPChannelProtocol,3,10.43.234.66] Unhandled Error
        Traceback (most recent call last):
          File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twisted/web/http.py", line 2145, in allContentReceived
            req.requestReceived(command, path, version)
          File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twisted/web/http.py", line 890, in requestReceived
            self.process()
          File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twisted/web/server.py", line 197, in process
            self.render(resrc)
          File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twisted/web/server.py", line 257, in render
            body = resrc.render(self)
        --- <exception caught here> ---
          File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/scrapyd/webservice.py", line 21, in render
            return JsonResource.render(self, txrequest).encode('utf-8')
          File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/scrapyd/utils.py", line 20, in render
            r = resource.Resource.render(self, txrequest)
          File "/root/.pyenv/versions/3.6.5/lib/python3.6/site-packages/twisted/web/resource.py", line 249, in render
            raise UnsupportedMethod(allowedMethods)
        twisted.web.error.UnsupportedMethod: Expected one of [b'HEAD', b'object', b'POST']
```

**Comment by Sudeepa14** [comment]
Isn't that simply saying GET requests are not allowed?

**Comment by Sudeepa14** [comment]
try http://localhost:6800/listprojects.json instead to see what are the current projects which are running. (I assume you got this error when you were trying to send a get request to [addversion.json](http://localhost:6800/addversion.json) endpoint / or if you used the browser)

**Comment by azmirfakkri** [comment]
@yanbyang did you find any solution for this issue?

**Comment by azmirfakkri** [comment]
My scrapyd log:

```
reclusa_1       | 2019-10-17T13:19:41+0000 [-] Scrapyd web console available at http://0.0.0.0:6800/
reclusa_1       | 2019-10-17T13:19:41+0000 [-] Loaded.
reclusa_1       | 2019-10-17T13:19:41+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 19.7.0 (/usr/local/bin/python 3.6.9) starting up.
reclusa_1       | 2019-10-17T13:19:41+0000 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
reclusa_1       | 2019-10-17T13:19:41+0000 [-] Site starting on 6800
reclusa_1       | 2019-10-17T13:19:41+0000 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site object at 0x7f2d71557048>
reclusa_1       | 2019-10-17T13:19:41+0000 [Launcher] Scrapyd 1.2.1 started: max_proc=16, runner='scrapyd.runner'
reclusa_1       | 2019-10-17T13:20:53+0000 [twisted.python.log#info] "192.168.48.1" - - [17/Oct/2019:13:20:52 +0000] "POST /schedule.json HTTP/1.1" 200 2049 "-" "python-requests/2.22.0"
reclusa_1       | 2019-10-17T13:30:29+0000 [twisted.python.log#info] "192.168.48.1" - - [17/Oct/2019:13:30:29 +0000] "GET / HTTP/1.1" 200 743 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
reclusa_1       | 2019-10-17T13:30:30+0000 [twisted.python.log#info] "192.168.48.1" - - [17/Oct/2019:13:30:30 +0000] "GET /favicon.ico HTTP/1.1" 404 153 "http://localhost:6800/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
reclusa_1       | 2019-10-17T13:30:33+0000 [twisted.python.log#info] "192.168.48.1" - - [17/Oct/2019:13:30:33 +0000] "GET /jobs HTTP/1.1" 200 471 "http://localhost:6800/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
reclusa_1       | 2019-10-17T13:30:38+0000 [twisted.python.log#info] "192.168.48.1" - - [17/Oct/2019:13:30:38 +0000] "GET /schedule.json HTTP/1.1" 200 544 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
reclusa_1       | 2019-10-17T13:31:29+0000 [twisted.web.http.HTTPChannel#info] Timing out client: IPv4Address(type='TCP', host='192.168.48.1', port=36206)
reclusa_1       | 2019-10-17T13:31:38+0000 [twisted.web.http.HTTPChannel#info] Timing out client: IPv4Address(type='TCP', host='192.168.48.1', port=36208)
reclusa_1       | 2019-10-17T13:35:57+0000 [twisted.python.log#info] "192.168.48.1" - - [17/Oct/2019:13:35:57 +0000] "GET / HTTP/1.1" 200 743 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36"
```

It looks like it did make a POST request for the first time and after that a GET request which is not supported and throwing an error.

**Comment by monamiiKe** [comment]
`"Traceback (most recent call last):\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\
runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapyd\\runner.py\", line 40, in <module>\r\n    main()\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapyd\\runner.py\", l
ine 37, in main\r\n    execute()\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\cmdline.py\", line 149, in execute\r\n    cmd.crawler_process = CrawlerProcess(settings)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\crawler
.py\", line 251, in __init__\r\n    super(CrawlerProcess, self).__init__(settings)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\crawler.py\", line 137, in __init__\r\n    self.spider_loader = _get_spider_loader(settings)\r\n  File \"C:\\Progr
amData\\Anaconda3\\lib\\site-packages\\scrapy\\crawler.py\", line 338, in _get_spider_loader\r\n    return loader_cls.from_settings(settings.frozencopy())\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\spiderloader.py\", line 61, in from_settin
gs\r\n    return cls(settings)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\spiderloader.py\", line 25, in __init__\r\n    self._load_all_spiders()\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\spiderloader.py\", line 47
, in _load_all_spiders\r\n    for module in walk_modules(name):\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\utils\\misc.py\", line 71, in walk_modules\r\n    submod = import_module(fullpath)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\impor
tlib\\__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\r\n  F
ile \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 668, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 638, in _load_backward_compatible\r\n  File \"c:\\users\\admini~1\
\appdata\\local\\temp\\monamii_rfq-1585012918-9oe2xprp.egg\\scrapyrfq\\spiders\\rfq.py\", line 27, in <module>\r\nModuleNotFoundError: No module named 'webhook'\r\n"`

> could you help me

**Comment by jpmckinney** [comment]
@monamiiKe See https://github.com/scrapy/scrapyd-client/issues/79 In the meantime, you will have to install your missing dependency in the same environment as scrapyd.

**Comment by jpmckinney** [comment]
The error seems to only occur when GETing a POST-only endpoint via a browser, which is the expected behavior.
