### ISSUE TITLE
start_pipeline: pgrp pipe: Too many open files in system

### ISSUE THREAD

**Issue by SimonWang00** [scrapy/scrapyd#290]
thank you first ! I use scrapyd to start the 30 crawler, and then enter the sehll command in the terminal window to prompt the above error. @rmax @decaz @dangra @eliasdorneles

**Comment by jpmckinney** [comment]
Depending on your OS, you might need to increase the limit on file descriptors.

On Linux, this is typically done with `ulimit`. Here are some docs (from Elasticsearch) about how to change the limit: https://www.elastic.co/guide/en/elasticsearch/reference/current/setting-system-settings.html#ulimit
