### ISSUE TITLE
Feature Request: Have recurring jobs with certain rules

### ISSUE THREAD

**Issue by MaxValue** [scrapy/scrapyd#297]
Hi! I am new to this tool, I have been a normal scrapy user until now.

### The problem
As far as I understand it, there is no way to set a spider to run again at some point. One would have to write some cron rules or something similar to re-run a spider.

### The idea
Have certain parameters/rules when defining a job which indicate if and when it should be re-run (this could then also include the desired start time).
This is just my opinion but I think using the `iCal` format as a base for the rule format would be good, since nothing new would be invented this way and it would be compatible to other tools (calendars mainly). And maybe there is already some Python module for parsing this format.

What do you think? Is this even wanted? Is this a good thing to have or should repetitions stay externally defined?

**Comment by my8100** [comment]
Now you can use the 'Timer Tasks' feature of [ScrapydWeb v1.2.0](https://github.com/my8100/scrapydweb/blob/master/HISTORY.md) to to schedule a spider run periodically.

**Comment by Digenis** [comment]
Hi @MaxValue,
There's no such plan to do this in scrapyd
but anyone is welcome to suggest how to implement this in a clean way
and create something useful not available in other tools.

Make sure to check out apache airflow, rundeck and apache chronos.

**Comment by jpmckinney** [comment]
Personally, I just use cron. Since the issue only receive one 👍  and no other participation, I will close it.
