### ISSUE TITLE
Why scrapyd can't read my custom environment variable while deploying a egg?

### ISSUE THREAD

**Issue by Levy96** [scrapy/scrapyd#301]
Firstly, the version of scrapyd is ``1.2.0``.
In my case, I need to set a environment variable, e.g. ``SPIDER_ENVIRONMENT`` which affects how Scrapy choose the configuration file.
Everything is ok when I run the code ``print os.environ['SPIDER_ENVIRONMENT']`` in Python shell.
I write some code in ``settings.py`` of my scrapy project. As shown below.
```Python
CONFIGURE = os.environ.get('SPIDER_ENVIRONMENT') or 'develop'
with open('/home/scrapy/test.log', 'w') as f:
    f.write('environment: ' + str(os.environ))
```
test.log was created after I call the ``addversion`` of scrapyd api , but there is no ``SPIDER_ENVIRONMENT`` in test.log.

**Comment by mojtabaasadi** [comment]
hi
seems scrapyd copies system env and updates then then runs spider with that .
try to restart scrapyd ( if you ran it with terminal restart that also ) then check if changes affected or not

**Comment by Levy96** [comment]
Thank you for replying :D
Everything works as respected after I restart scrapyd. I think my question has been resolved, so I'd like to close this.
