### ISSUE TITLE
Read configuration from environment variables

### ISSUE THREAD

**Issue by fabiomolinar** [scrapy/scrapyd#303]
[**feature request**]
It would be nice if it would be possible to read configuration settings from environment variables. That way it gets easy and simple to have different configuration settings for different environments.

Say, for dev:
```
[scrapyd]
debug = on
```

And on prod:
```
[scrapyd]
debug = off
```

An approach similar to `scrapy` settings would be great. That way we could simply:
`DEBUG = os.environ.get('SCRAPYD_DEBUG', 'on')`

**Comment by fabiomolinar** [comment]
In my case, I am using docker-compose and I have different environment variable files used depending on the environment I am working.
In case someone is in the same situation as I am, here is the workaround I have found up until now:

Define an entrypoint script to run before the scrapyd command.
```
ENTRYPOINT [ "entrypoint.sh" ]
CMD [ "scrapyd" ]
```

On the entrypoint script, check the environment variables and modify the .conf file accordingly.
```
if [ ! -z "$PROJECT_DEBUG" ] && [ "$PROJECT_DEBUG" = "True" ]; then
    sed -i "s/debug = off/debug = on/" ./scrapyd/scrapyd.conf
fi
exec "$@"
```

**Comment by jpmckinney** [comment]
In my own deployment of Scrapyd, I simply have SaltStack rewrite `.scrapyd.conf` and restart Scrapyd if there were changes.

**Comment by jpmckinney** [comment]
If other deployment scenarios, like Docker, you can either replace values using `sed` as above, or you can construct the file from scratch, using environment variables with default values, e.g. 

```
echo "[scrapyd]
jobs_to_keep = ${JOBS_TO_KEEP:=5}
# etc.
" > ./scrapyd/scrapyd.conf
```

So, until a clear need is expressed, I will close the issue. Given limited maintainer capacity, I think it is best to focus on features that have no good alternative implementation outside Scrapyd.

**Comment by NeilClack** [comment]
So is it my understanding that I can't utilize environment variables for secret information?

**Comment by jpmckinney** [comment]
Why do you need the secrets to be in the environment? Why not in a file that only the Scrapyd process can read?

**Comment by NeilClack** [comment]
Database connection strings are secret as well and are normally pulled via environment variables into Python during development, and I'd expect my deployment to do the same.

**Comment by jpmckinney** [comment]
Scrapyd doesn't interface with databases. If you're connecting to databases from Scrapy (no "d"), then you can use environment variables, since it'll be in your own code.
