### ISSUE TITLE
All of spider process exit at the same time.

### ISSUE THREAD

**Issue by Levy96** [scrapy/scrapyd#306]

**Comment by Levy96** [comment]
I started 23 process by scrapyd, but all of them exited with the log such as 
``2019-01-11T17:18:21+0800 [-] Process died: exitstatus=None  project='crawler' spider='geshui_sxs' job='aa0ad5d8156f11e985f600163e08e9d5' pid=682 log='logs/crawler/geshui_sxs/aa0ad5d8156f11e985f600163e08e9d5.log' items=None``.

I use the default config covered with ``max_proc = 40``.

**Comment by Levy96** [comment]
It is worth mentioning that spider process exit after several hours rather than exiting immediately. And there are no coding errors in spider.

**Comment by Digenis** [comment]
Hi @Levy96,
what did the scrapy log contain?
