### ISSUE TITLE
Hello，who can help me

### ISSUE THREAD

**Issue by xy-angee** [scrapy/scrapyd#307]

**Comment by xy-angee** [comment]
I want to  modify the schedule.json api. I want to modify it's response. Who can help me?

**Comment by Apuyuseng** [comment]
Maybe you can modify `/scrapyd/webservice.py` file.
```python 
class Schedule(WsResource):
       pass
```

**Comment by Digenis** [comment]
@xy-angee,

Folllow the example in webservice.py to write a module with a webservice
Build a package for your module using setuptools
Install your package in the same environment in which scrapyd runs
Enable your webservice in your scrapyd configration file
