### ISSUE TITLE
Twisted 19.2.0 assumes http headers are of string type

### ISSUE THREAD

**Issue by Luke-Shepp** [scrapy/scrapyd#311]
After trying to run scrapyd on both MacOS Mojave, and a fresh AWS instance based on AMI `ami-0ff760d16d9497662`, I'm always hitting the same error.

Steps are as follows:
~~~
curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
sudo python get-pip.py
sudo yum install gcc
sudo yum install python-devel
sudo pip install scrapyd
vi scrapyd.conf
scrapyd
~~~

The contents of scrapyd.conf are that of the [example](https://scrapyd.readthedocs.io/en/stable/config.html#example-configuration-file), with the addition of a different bind_address:
~~~
[scrapyd]
eggs_dir    = eggs
logs_dir    = logs
items_dir   =
jobs_to_keep = 5
dbs_dir     = dbs
max_proc    = 0
max_proc_per_cpu = 4
finished_to_keep = 100
poll_interval = 5.0
http_port   = 6800
debug       = off
runner      = scrapyd.runner
application = scrapyd.app.application
launcher    = scrapyd.launcher.Launcher
webroot     = scrapyd.website.Root
bind_address = 0.0.0.0

[services]
schedule.json     = scrapyd.webservice.Schedule
cancel.json       = scrapyd.webservice.Cancel
addversion.json   = scrapyd.webservice.AddVersion
listprojects.json = scrapyd.webservice.ListProjects
listversions.json = scrapyd.webservice.ListVersions
listspiders.json  = scrapyd.webservice.ListSpiders
delproject.json   = scrapyd.webservice.DeleteProject
delversion.json   = scrapyd.webservice.DeleteVersion
listjobs.json     = scrapyd.webservice.ListJobs
daemonstatus.json = scrapyd.webservice.DaemonStatus
~~~

However, when trying to run `scrapyd-deploy`, or even browse to `:6800/jobs`, The following error is thrown:
~~~
2019-04-11T08:55:33+0000 [twisted.python.log#info] "_redacted_" - - [11/Apr/2019:08:55:33 +0000] "GET /jobs HTTP/1.1" 500 6077 "http://_redacted_:6800/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.103 Safari/537.36"
2019-04-11T08:55:33+0000 [twisted.web.server.Request#critical]
	Traceback (most recent call last):
	  File "/usr/lib64/python2.7/site-packages/twisted/protocols/basic.py", line 572, in dataReceived
	    why = self.lineReceived(line)
	  File "/usr/lib64/python2.7/site-packages/twisted/web/http.py", line 2105, in lineReceived
	    self.allContentReceived()
	  File "/usr/lib64/python2.7/site-packages/twisted/web/http.py", line 2196, in allContentReceived
	    req.requestReceived(command, path, version)
	  File "/usr/lib64/python2.7/site-packages/twisted/web/http.py", line 920, in requestReceived
	    self.process()
	--- <exception caught here> ---
	  File "/usr/lib64/python2.7/site-packages/twisted/web/server.py", line 199, in process
	    self.render(resrc)
	  File "/usr/lib64/python2.7/site-packages/twisted/web/server.py", line 259, in render
	    body = resrc.render(self)
	  File "/usr/lib/python2.7/site-packages/scrapyd/website.py", line 157, in render
	    txrequest.setHeader('Content-Length', len(s))
	  File "/usr/lib64/python2.7/site-packages/twisted/web/http.py", line 1271, in setHeader
	    self.responseHeaders.setRawHeaders(name, [value])
	  File "/usr/lib64/python2.7/site-packages/twisted/web/http_headers.py", line 220, in setRawHeaders
	    for v in self._encodeValues(values)]
	  File "/usr/lib64/python2.7/site-packages/twisted/web/http_headers.py", line 40, in _sanitizeLinearWhitespace
	    return b' '.join(headerComponent.splitlines())
	exceptions.AttributeError: 'int' object has no attribute 'splitlines'
~~~

Some versions:
~~~
# python --version
Python 2.7.5
# twistd --version
twistd (the Twisted daemon) 19.2.0
Copyright (c) 2001-2019 Twisted Matrix Laboratories.
See LICENSE for details.
~~~

![Screenshot 2019-04-11 at 10 10 57](https://user-images.githubusercontent.com/35956374/55945153-216e8980-5c42-11e9-8750-c10f77dd9b05.png)

**Comment by HaoweiCh** [comment]
same err here

**Comment by hellobiek** [comment]
same error +1

**Comment by hellobiek** [comment]
downgrade Twisted to verison 18.9.0 can fix this problem.

`pip3 install Twisted==18.9.0`

**Comment by Luke-Shepp** [comment]
Downgrading to Twisted 18.9.0 seems to solve it here too 👍

**Comment by my8100** [comment]
Why not changed the title to ```Twisted 19.2.0 raises exceptions.AttributeError: 'int' object has no attribute 'splitlines'```

**Comment by my8100** [comment]
@Digenis This issue is much more urgent, please check out https://github.com/my8100/scrapyd/commit/298ba7220744c7491aa4e21934ae99ce45025977

**Comment by Digenis** [comment]
I think https://github.com/twisted/twisted/commit/fd2fbf4bc4889d6d92350c37a0f05aa3ee9ba687#diff-effe5888987605608f990d71470cc65d broke it.

@my8100, open a PR specifically for the patch in https://github.com/my8100/scrapyd/commit/298ba7220744c7491aa4e21934ae99ce45025977 and I'll merge it.
Don't forget to fix your gitignore.

**Comment by my8100** [comment]
`.idea` in the gitignore file is useful when using PyCharm, you can refer to https://github.com/scrapy/scrapy/blob/master/.gitignore

**Comment by my8100** [comment]
@Digenis Done.

**Comment by patalanov** [comment]
I have this error with `Twisted==17.9.0`as well.

**Comment by Digenis** [comment]
@patalanov,
Are you sure it's the same issue?
Post here scrapyd's output (when running from the console)
and scrapyd-deploy's output.

**Comment by patalanov** [comment]
I'm running scrapyrt as a docker service container, built like so:
```

  scrapyrt:
    image: vimagick/scrapyd:py3
    command: scrapyrt -i 0.0.0.0 -p 9080
    restart: always
    ports:
      - '9080:9080'
    volumes:
      - ./services/web:/usr/src/app
    working_dir: /usr/src/app/project/api
    depends_on:
      - web

```
This is how I request scrapy results:

```
    params = {
            'spider_name': str(spider),
            'start_requests':True
            }
    # scrape items
    response = requests.get('http://localhost:9080/crawl.json', params)
    print (response.text)
```
I had `Twisted==17.9.0`, upgraded to match `Twisted==18.9.0` in my `requeriments.txt`, and when I:

 `curl -v "http://localhost:9080/crawl.json" | jq`, I get the same error:

```
scrapyrt_1         | Traceback (most recent call last):
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 199, in process
scrapyrt_1         |     self.render(resrc)
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/web/server.py", line 259, in render
scrapyrt_1         |     body = resrc.render(self)
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/scrapyrt/resources.py", line 31, in render
scrapyrt_1         |     return self.render_object(result, request)
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/scrapyrt/resources.py", line 95, in render_object
scrapyrt_1         |     request.setHeader('Content-Length', len(r))
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/web/http.py", line 1271, in setHeader
scrapyrt_1         |     self.responseHeaders.setRawHeaders(name, [value])
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/web/http_headers.py", line 220, in setRawHeaders
scrapyrt_1         |     for v in self._encodeValues(values)]
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/web/http_headers.py", line 220, in <listcomp>
scrapyrt_1         |     for v in self._encodeValues(values)]
scrapyrt_1         |   File "/usr/local/lib/python3.5/dist-packages/twisted/web/http_headers.py", line 40, in _sanitizeLinearWhitespace
scrapyrt_1         |     return b' '.join(headerComponent.splitlines())
scrapyrt_1         | AttributeError: 'int' object has no attribute 'splitlines'
```

**Comment by Digenis** [comment]
```
File "/usr/local/lib/python3.5/dist-packages/scrapyrt/resources.py", line 95, in render_object
  request.setHeader('Content-Length', len(r))
```
This means that you are using scrapyd-1.2 from pypi

```
File "/usr/local/lib/python3.5/dist-packages/twisted/web/http_headers.py", line 40, in _sanitizeLinearWhitespace
  return b' '.join(headerComponent.splitlines())
```
This means that your scrapyd is using Twisted-19.2

You need to figure out how to properly upgrade packages in the environment that scrapyd is using.

I'll cherry-pick this in a bugfix release in scrapyd-1.2
(although the "correct" way would be to limit twisted to <1.9.2)

**Comment by patalanov** [comment]
so packages from docker `image: vimagick/scrapyd:py3`  are overriding `requirements.txt` versions at built time...
is it possible do that proper upgrade in a dockerfile?

**Comment by Digenis** [comment]
@patalanov I didn't notice earlier that you refer to scrapyrt.
It's a different project. This is not a scrapyd bug.
Continued at https://github.com/scrapinghub/scrapyrt/pull/84

**Comment by my8100** [comment]
@patalanov 
Try adding `RUN pip install Twisted==18.9.0` after `RUN pip install /scrapyrt/src` in the [Dockerfile](https://github.com/scrapinghub/scrapyrt/blob/master/Dockerfile).

**Comment by patalanov** [comment]
@my8100 
I can't make this work...
I'm pulling the image `image: vimagick/scrapyd:py3` in a docker container, so thats the image Dockerfile.
```
 scrapyrt:
    image: vimagick/scrapyd:py3
    command: scrapyrt -i 0.0.0.0 -p 9080
    restart: always
    ports:
      - '9080:9080'
    volumes:
      - ./services/web:/usr/src/app
    working_dir: /usr/src/app/project/api
    depends_on:
      - web
```
Do I have to build it from scratch using that dockerfile in order to make this work??

**Comment by my8100** [comment]
@patalanov 
The key point is *requirements.txt*  **is not read** by service scrapyrt in *docker-compose.yml*:
1. Make sure these files are in the same dir
```
Dockerfile
docker-compose.yml
entrypoint.sh
requirements.txt
```
2. Update *docker-compose.yml*, note that `command` is replaced with `entrypoint`
```
 scrapyrt:
    image: vimagick/scrapyd:py3
    restart: always
    ports:
      - '9080:9080'
    volumes:
      - ./:/codes
      - ./services/web:/usr/src/app
    working_dir: /usr/src/app/project/api
    entrypoint: /codes/entrypoint.sh
    depends_on:
      - web
```
3. New *entrypoint.sh*
```
#!/bin/sh
apt-get update
apt-get install -y gcc
pip install -r /codes/requirements.txt
/usr/local/bin/scrapyrt -i 0.0.0.0 -p 9080
```
4. New *requirements.txt*
```
pip>=19.1.1
Twisted==18.9.0
```

**Comment by patalanov** [comment]
oh man, thank you so much...
I have, however, many services (and I hereby only show 'web') 
organized like so:

```
 docker-compose.yml/
                   web/
                      project/
                             api/
                                scrapy.cfg
                                blogs/
                                     items.py
                                     middlewares.py
                                     settings.py
                                        spiders/
                                           
```
so docker-compose.yml cannot be in same directory..
could you be extra kind and edit your configuration according to mine?
I would appreciate it very much

**Comment by my8100** [comment]
@patalanov 
1. New files `entrypoint.sh` and `requirements.txt` in dir `./services/web`
2. Update docker-compose.yml
```
 scrapyrt:
    image: vimagick/scrapyd:py3
    restart: always
    ports:
      - '9080:9080'
    volumes:
      - ./services/web:/usr/src/app
    working_dir: /usr/src/app/project/api
    entrypoint: /usr/src/app/entrypoint.sh
    depends_on:
      - web
```
3. *entrypoint.sh*, remember to `execute chmod +x entrypoint.sh`
```
#!/bin/sh
apt-get update
apt-get install -y gcc
pip install -r /usr/src/app/requirements.txt
/usr/local/bin/scrapyrt -i 0.0.0.0 -p 9080
```

**Comment by patalanov** [comment]
@my8100 

thanks a lot, your solution works like a charm from my host.

my web container, however, must make requests to scrapyrt via:

`    response = requests.get('http://scrapyrt:9080/crawl.json', params)
`

because host must have the service name (`scrapyrt` instead of `localhost`), or you'll get `HTTPConnectionPool Error`.

would that change anything in your configuration above?

**Comment by my8100** [comment]
@patalanov 
Nothing to change as the service still named 'scrapyrt'.

**Comment by patalanov** [comment]
perfect, it crawls, and logs to file:

`2019-05-23 05:13:07 [scrapy] DEBUG: Crawled (200) <GET http://web.archive.org/web/20160803191321/https://www.allmusic.com/mood/sweet-xa0000000773/songs> (referer: None)
2019-05-23 05:13:09 [scrapy] INFO: Closing spider (finished)
2019-05-23 05:13:09 [scrapy] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 287,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'downloader/response_bytes': 24912,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 5.068044,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2019, 5, 23, 5, 13, 9, 885999),
 'item_scraped_count': 56,
 'log_count/DEBUG': 57,
 'log_count/INFO': 6,
 'memusage/max': 49070080,
 'memusage/startup': 49070080,
 'response_received_count': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2019, 5, 23, 5, 13, 4, 817955)}`

but I'm not being able to `parse` and print results within my crawling function:

    params = {
            'spider_name': spider,
            'start_requests':True
            }
    response = requests.get('http://scrapyrt:9080/crawl.json', params)
    data = response.json()
    data_text = response.text
    print (data_text, data)

any reason for that? is this related to the previous bug or am I just missing something?

**Comment by patalanov** [comment]
Everything works fine now. Bug is gone, data crawled and parsed. Thank you for being so helpful and kind, @my8100

**Comment by my8100** [comment]
> I'll cherry-pick this in a bugfix release in scrapyd-1.2
> because there are enough duplicate issues already.

@Digenis, Why not upload v1.2.1 to PyPI, which just merged #316 based on v1.2.0

**Comment by MoritzMK** [comment]
I've downgraded Twisted to 18.9.0 but with python 3.6 and python 3.7 i didn't get it to work.
Is there another workaround for this then waiting for v.1.2.1?

**Comment by Digenis** [comment]
Hi @MoritzMK, scrapyd-1.2.1 was released 2 days ago.
