### ISSUE TITLE
who can help me?

### ISSUE THREAD

**Issue by huozhenlin** [scrapy/scrapyd#313]
that's a problem in scrapyd works on docker。int' object has no attribute 'splitlines
![image](https://user-images.githubusercontent.com/19356940/56121886-b6a3b200-5fa3-11e9-9b82-3e76d157e592.png)

**Comment by my8100** [comment]
Check out #311

**Comment by Digenis** [comment]
Fixed in #316.
@huozhenlin, until a new release is published
you can use either downgrade twisted to 18.9.0 (as some people suggest in #311)
or install the master branch from this repo.
