### ISSUE TITLE
 limit the same spider

### ISSUE THREAD

**Issue by Ericliuzi** [scrapy/scrapyd#322]
How limit the same spider?
A spider cannot run in the frequency range. For example, a spider runs once every 5 minutes, but it may be blocked. It runs 4 after 20 minutes.

**Comment by Digenis** [comment]
Hi @Ericliuzi,
the scrapyd issue tracker is for reporting/fixing bugs, discussing features etc.
For usage questions try stackoverflow, reddit or irc https://scrapy.org/community/
