### ISSUE TITLE
Add more environments to tox

### ISSUE THREAD

**Issue by Digenis** [scrapy/scrapyd#323]
We claim to support a wide version range for required packages.
Multiplied, they produce a huge number of possible environments.
We should at least try all the supported scrapy releases and some twisted releases.

**Comment by jpmckinney** [comment]
Related: https://github.com/scrapy/scrapyd-client/issues/86

**Comment by jpmckinney** [comment]
Scrapyd no longer uses `tox` as of 3ed9b89e3e0a9bdaf34487e7fc3da7cf463e7250.

While it would be best to test against multiple versions, I think in practice all that we have the capacity to do is fix the `install_requires` when we learn that some old version no longer works.
