### ISSUE TITLE
log encoding and charset header

### ISSUE THREAD

**Issue by Digenis** [scrapy/scrapyd#342]
Currently scrapy uses utf-8 in the logs by default.
Scrapyd's responses when sending the logs don't set a charset
and users are presented with gibberish instead of non-ascii text.

Many decisions in scrapyd are already based on scrapy's default configuration
and, anyway, anyone changing the utf-8 default to a different encoding is asking for trouble.

**Comment by jpmckinney** [comment]
Is the solution to set a charset for the log file?

Or is this a non-issue? I can read logs that contain UTF-8 characters, whether in the browser or on the command-line, and they are not gibberish.

**Comment by jpmckinney** [comment]
Closing as cannot reproduce the issue.

**Comment by Digenis** [comment]
It was the browsers' encoding detection that wasn't favoring utf8 as much as it should.
Maybe now it does.
