### ISSUE TITLE
no active project

### ISSUE THREAD

**Issue by sulthonzh** [scrapy/scrapyd#352]
![image](https://user-images.githubusercontent.com/4921059/63279403-1c49d700-c2d3-11e9-9cb8-75ee42f1713f.png)
how to fix this issue, 
im using scrapy 1.7.3

I think this happened because scrapy.cfg was not found, then how to solve it?, I have included it in the egg file but it's still an error

**Comment by my8100** [comment]
Which API are you calling?
Check whether the target project still exists first. 
```
$ curl http://localhost:6800/listprojects.json
```

**Comment by sulthonzh** [comment]
that's my bad, that's weird, I just reinstalled the 'scrapy' and worked
