### ISSUE TITLE
cancel.json unable to cancel tasks

### ISSUE THREAD

**Issue by kjxy** [scrapy/scrapyd#356]
```curl http://192.168.1.1:100/cancel.json -d project=Scrapy -d job=da045f 7ed9bf11e9a89d0242ac110004```
```{"node_name": "332e7d9a8e6a", "status": "ok", "prevstate": "running"}```
But...The mission has not been stopped.

scrapyweb v1.1.0

**Comment by my8100** [comment]
You can execute cancel.json twice to force shutdown the job.

**Comment by kjxy** [comment]
```curl http://192.168.1.1:100/cancel.json -d project=Scrapy -d job=da045f 7ed9bf11e9a89d0242ac110004```  

The third...

The mission has not been stopped.

**Comment by my8100** [comment]
Are you using Selenium in your spider?
It may be the cause.

**Comment by kjxy** [comment]
> Are you using Selenium in your spider?
> It may be the cause.

Not using Selenium. Need a version upgrade? The job has been running for three days.

**Comment by my8100** [comment]
Can you post the related log of Scrapyd and your spider after executing cancel.json

**Comment by kjxy** [comment]
> 执行cancel.json后，您能否发布Scrapyd和您的Spider的相关日志

Fine. Now can only stop the task through docker

**Comment by Dashu-Xu** [comment]
> Are you using Selenium in your spider?
> It may be the cause.

hi, i'm using selenium in my project , after finish job, the `geckodriver` not quit thus the job still show under the running item, is there any solution for that ?

**Comment by jpmckinney** [comment]
@Dashu-Xu I think your issue is #83.

For @kjxy's issue, it would have helped to know the log output for the spider. It would be expected to have a message:

> Received SIGTERM, shutting down gracefully. Send again to force

And then another message when the next SIGTERM was sent.
