### ISSUE TITLE
/usr/local/bin/scrapyd-deploy:23: ScrapyDeprecationWarning: Module `scrapy.utils.http` is deprecated,

### ISSUE THREAD

**Issue by gusevmaksim** [scrapy/scrapyd#362]
/usr/local/bin/scrapyd-deploy:23: ScrapyDeprecationWarning: Module `scrapy.utils.http` is deprecated, Please import from `w3lib.http` instead.
Scrapy (1.8.0)

**Comment by sayhellotogithub** [comment]
you can see https://www.cnblogs.com/lutt/p/12344990.html, just replace

**Comment by yashsandansing** [comment]
> 
> 
> you can see https://www.cnblogs.com/lutt/p/12344990.html, just replace

The whole page is in chinese

**Comment by jpmckinney** [comment]
Fixed in scrapy/scrapyd-client#82
