### ISSUE TITLE
Need add auth for scrapy to protect it from attack when expose it to internat.

### ISSUE THREAD

**Issue by tinybright** [scrapy/scrapyd#363]
If I expose it to the internat,everyone can controller my server by add project in my scrapyd.Today I found kinsing and kdevtmpfsi in my server. And I found a project named Evil in my scrapyd.You can check it if you expose your scrapyd to internat.

**Comment by my8100** [comment]
See https://github.com/my8100/files/blob/master/scrapyd-basic-auth/README.md

**Comment by tinybright** [comment]
close
