### ISSUE TITLE
Adding support for a database?

### ISSUE THREAD

**Issue by sluceno** [scrapy/scrapyd#365]
Hi,

I am wondering how it would be seen to add support for postgres or some kind of database. Probably redis is not a bad idea as well.

The idea behind is to be able to scale horizontally, having a shared database among the different scrapyd processes would do the trick.

Thanks

**Comment by my8100** [comment]
Maybe you could try #359 first and give some feedback?

**Comment by sluceno** [comment]
thank for your answer.

We will take a look for sure in the near future. Will let you know

**Comment by Digenis** [comment]
Related: #197

**Comment by jpmckinney** [comment]
What would be the purpose of the database? As an alternative to the sqlite DB, or for some other purpose?

**Comment by jpmckinney** [comment]
Closing as no response to question in several months.
