### ISSUE TITLE
Pass argument from curl to spider class

### ISSUE THREAD

**Issue by ghost** [scrapy/scrapyd#374]
I have try to pass argument (file_path) from curl to spider so as to setup the custom_setting. I have try two of method shown in https://docs.scrapy.org/en/0.16/topics/scrapyd.html#schedule-json
Method 1:

```
class MySpider(scrapy.Spider):
    name = 'MySpider'

    custom_settings = { 'FEED_URI': self.file_path }
```

Method 2:
```
class MySpider(scrapy.Spider):
    name = 'MySpider'

    def __init__(self, file_path ='', **kwargs):
        custom_settings = {
            'FEED_URI' :  file_path + '.json'
        }
        super(MySpider,self).__init__(**kwargs)
```

But both of the method cant set the custom_settings in Myspider class

**Comment by jpmckinney** [comment]
You can do something like:

```
curl http://localhost:6800/schedule.json -d project=projectname -d spider=spidername -d setting=FEED_URI=value
```

And remove the `custom_settings`.
