### ISSUE TITLE
Access Scraped Items

### ISSUE THREAD

**Issue by Muhammad-Saqib-980** [scrapy/scrapyd#376]
Hi, I was trying to use scrapyd it is a great tool but i am having a issue i add job, job runs fine everying in log files is fine but i am not able to locate Scraped Items Please guide me how i can access items scraped by spider. I try to find it online some i got a page where jobs table contains link to items like
![image](https://user-images.githubusercontent.com/50771695/81439225-78b59500-9187-11ea-9b7c-e91b8f1507e5.png)
but i am getting table like
![image](https://user-images.githubusercontent.com/50771695/81439299-9daa0800-9187-11ea-80b1-b13bbebe2041.png)
Please guide me

**Comment by my8100** [comment]
https://scrapyd.readthedocs.io/en/stable/config.html#items-dir

**Comment by jpmckinney** [comment]
@my8100 shared the relevant configuration to set.
