### ISSUE TITLE
Running scrapyd in python3

### ISSUE THREAD

**Issue by Tobeyforce** [scrapy/scrapyd#379]
Hi,
Is there any way to run scrapyd in python3? The docs say it's supported but I can't really find more info on how to make sure it actually runs in python3. By default, on my ubuntu machine, it seems to run on python 2.7.

**Comment by my8100** [comment]
FYI:
https://scrapyd.readthedocs.io/en/stable/news.html?highlight=python#id2

1.2.0
Release date: 2017-04-12
The highlight of this release is the long-awaited Python 3 support.
