### ISSUE TITLE
'heavy' spider arguments yield OSError in schedule.json action

### ISSUE THREAD

**Issue by ilias-ant** [scrapy/scrapyd#381]
**Summary**
When a rather "data-heavy" keyword argument is passed into `POST schedule.json` action, it yields the following error:
```shell
... b'-a', b'_job=e40210a6c52911ea9de2d8f2ca734204'] in environment id 140511990166440
	:Traceback (most recent call last):
	  File "/home/iantonopoulos/projects/sample-project/sample-project-env/lib/python3.6/site-packages/twisted/internet/process.py", line 406, in _fork
	    environment)
	  File "/home/iantonopoulos/projects/sample-project/sample-project-env/lib/python3.6/site-packages/twisted/internet/process.py", line 484, in _execChild
	    os.execvpe(executable, args, environment)
	  File "/usr/lib/python3.6/os.py", line 568, in execvpe
	    _execvpe(file, args, env)
	  File "/usr/lib/python3.6/os.py", line 583, in _execvpe
	    exec_func(file, *argrest)
	OSError: [Errno 7] Argument list too long: '/home/iantonopoulos/projects/sample-project/sample-project-env/bin/python3'
2020-07-13T19:57:13+0300 [-] Process died: exitstatus=1  project='foo_project' spider='foo_spider' job='e40210a6c52911ea9de2d8f2ca734204' pid=28246 log='/home/iantonopoulos/projects/sample-project/logs/foo_project/foo_spider/e40210a6c52911ea9de2d8f2ca734204.log' items=None
```
**Steps to Reproduce**
I will layout a Pythonic reproduction strategy, that uses _Python 3.6.9_ in _Ubuntu 18.04.4 LTS_. It requires the following libraries:

- scrapy==2.1.0
- scrapyd==1.2.1
- python-scrapyd-api==2.1.2

Let's assume a `foo_project` Scrapy project has been created with a simple `foo_spider`. This spider has a single spider argument called `product_urls` which is used as the crawling basis. Scrapy project is deployed to a localhost Scrapyd webservice via `POST addversion.json`.

Then:

```python
import json

from scrapyd_api import ScrapydAPI


scrapyd = ScrapydAPI()
# product_urls has a string length of 131040 - it is scheduled correctly.
scrapyd.schedule(project='foo_project', spider='foo_spider', product_urls=json.dumps(["http://www.example.com"] * 5040)) 
# product_urls has a string length of 131066 - it yields the above OSError!
scrapyd.schedule(project='foo_project', spider='foo_spider', product_urls=json.dumps(["http://www.example.com"] * 5041)) 
```

With small increases in the string length of the `product_urls` argument, I've found that the breaking point is at length: `131058`

**Expected Results**
`POST schedule.json` should allow for an arbitrary number of keyword arguments, each with a sensible size as most of the times these keyword arguments may host extensive lists of URLs for crawling.

**Actual Results**
`POST schedule.json` with a keyword argument of string length >= 131058 yields `OSError`.

---
**_update_**: probably has to do with [MAX_ARG_STRLEN (131072)](https://www.in-ulm.de/~mascheck/various/argmax/), right ?

**Comment by Digenis** [comment]
If it's an OSError, there's not much we can do.

As the spider parameters grow,
they become more of a data pipeline than parametrization.

How can scrapyd do data pipelines?
There's a lot to discuss but not in the context of this issue.
I think most people prefer to do their own data pipelines.
E.g. here, one would probably pass a key to a key-value store
or a url to an internal service where the full list of urls would be available.
There's nothing that scrapyd can do to improve this
except for solving issues such as #55 
to help users better integrate their task schedulers with scrapyd.

**Comment by ilias-ant** [comment]
thanks for the answer (and the suggestion!) @Digenis

i thought of closing the issue after i too realized that this is an OSError  (and thus unrelated to the Scrapyd functionality), but i chose to leave it a bit longer, more as a reference point for future developers that may be buffled over this :)

I think now the time has come, and your suggestion will be of great value!

**Comment by Digenis** [comment]
I forgot to add that the spider's start_urls can have a url with the `file:///` scheme
