### ISSUE TITLE
More details in the Jobs table

### ISSUE THREAD

**Issue by Blender3D** [scrapy/scrapyd#39]
The Jobs table in the web interface is really bare. The Scrapy stats collector contains a lot of valuable data, which should be included in this table.

I see a few ways of accessing this data:
1. Parsing logs. This seems like unnecessary work and will only give access to crawl statistics after a crawl has finished.
2. Subclassing `CrawlerProcess`, overriding methods that start/stop the reactor, thus removing the need to launch `scrapyd.runner` as a separate process. This gives us direct access to `crawler.stats.get_stats()` and gives the added benefit of using only one reactor to run multiple crawls.
3. Using `scrapy.contrib.webservice.stats.StatsResource`. This doesn't rely on an unstable API (unlike 2), but will force us to parse log files to determine the webservice port.

Scrapyd needs some useful upgrades aside from a prettier UI. Scheduling periodic crawls, queues, retrying, etc. They don't seem difficult to implement, but I don't have the time to do this myself and don't know if the community even has interest in Scrapyd.

Thoughts?

**Comment by my8100** [comment]
Try this https://github.com/my8100/scrapydweb **Full-featured web UI for Scrapyd cluster management, Scrapy log analysis and visualization**

**Comment by jpmckinney** [comment]
Closing as this feature request has not attracted additional interest since 2014.
