### ISSUE TITLE
Expected one of [b'HEAD', b'object', b'POST'] when sending pre-flight OPTIONS request

### ISSUE THREAD

**Issue by gymcoding** [scrapy/scrapyd#391]
The following error occurs when you request http://localhost:6800/schedule.json with Axios:

Error Message
```sh
Expected one of [b'HEAD, b'object, b'POST']
```

The cause is an error caused by pre-flight (OPTIONS) prior to POST request.

How should I handle this?

**Comment by Digenis** [comment]
If it's not returning 405, it's a scrapyd or twisted bug.

If it's returning 405, its an axios bug.

In any case, if this method is useful,
feel free to open a pull request and add it to the webservice
