### ISSUE TITLE
SqlitePriorityQueue.pop() return None may crash Poller.poll() 

### ISSUE THREAD

**Issue by aspidites** [scrapy/scrapyd#40]
Continued discussion of scrapy/scrapy#28 here since it is directly related to scrapyd.

I can think of a few different ways to handle this, but until I get more familiar with scrapy(d)'s internals, I'm not sure which is preferable:
1. Impement for fine-grained control over sqlite3's transactions
2. Increase the timeout limit
3. Test for an ongoing transaction before hand

I suspect 1 would be most robust but 3 would be least intrusive.

Is it enough to change `scrapyd/sqlite.py` line 14 to:

``` pyhon
self.conn = sqlite3.connect(self.database, isolation_level=None, check_same_thread=False)
```

? If so, we could also remove explicit calls to `commit()` since they would be committed automatically after `execute()`

**Comment by Digenis** [comment]
I quote here the original ticket to make it easier to read all the details in one place

@shaneaevans wrote:
>Previously reported by mrkschan on Trac http://dev.scrapy.org/ticket/313

>I have a scrapy project that has several spiders in it. Those spiders are scheduled to execute on an hourly-basis.

>The scrapyd eventually report unhandled error (as shown below). When I dig through the source of scrapy, I suspect the concurrent control of sqlite3 access is not well guarded as the error below is caused by popping from an empty queue.

>The case can simply be explained by the scenario with two spiders A and B (also refer to the source - http://is.gd/ht4HSs).

>1. Spider A's poller poll() get to line 21 of scrapyd/poller.py.
2. Meanwhile, Spider B's poller also get to line 21.
3. Spider A's poller poll() get to line 23, the queue in sqlite becomes empty and sqlite3 is locked (according to py doc - http://is.gd/67PKpn).
4. Spider B's poller poll() also get to line 23, wait the lock to be released.
5. Spider A commit and release the sqlite lock.
6. Spider B pop() from an empty queue. Raise Error.

>```
Traceback (most recent call last):
  File "/usr/lib/python2.6/dist-packages/twisted/internet/base.py", line 778, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/task.py", line 194, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 117, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 944, in unwindGenerator
    return _inlineCallbacks(None, f(*args, **kwargs), Deferred())
--- <exception caught here> ---
  File "/usr/lib/python2.6/dist-packages/twisted/internet/defer.py", line 823, in _inlineCallbacks
    result = g.send(result)
  File "/usr/lib/pymodules/python2.6/scrapyd/poller.py", line 24, in poll
    returnValue(self.dq.put(self._message(msg, p)))
  File "/usr/lib/pymodules/python2.6/scrapyd/poller.py", line 33, in _message
    d = queue_msg.copy()
exceptions.AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by Digenis** [comment]
Python has a builtin priority queue that handles locking.
https://docs.python.org/2/library/queue.html
I think we should consider rewriting the SqlitePriorityQueue around it.
Also, since the two uses of sqlite in the priority queue
are filesystem persistence and concurrency in polling,
it's possible to drop it completely.

**Comment by Digenis** [comment]
Quoting @bezkos from the mailing list
with some additional notes of mine:

> I patched two production servers with changes.
> I use one server/scrapyd instance to populate shared queue with new records and consume, and the 2nd one only consume records from shared queue.
> So I have 2 scrapyd instances on different servers
> consuming records from same shared queue.
> This scenario worked well for some hours but I am in front of this bug now https://github.com/scrapy/scrapyd/issues/40

```
Traceback (most recent call last):
  File "/root/mysite/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/root/mysite/local/lib/python2.7/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
  File "/root/mysite/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 149, in maybeDeferred
    result = f(*args, **kw)
  File "/root/mysite/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1331, in unwindGenerator
    return _inlineCallbacks(None, gen, Deferred())
--- <exception caught here> ---
  File "/root/mysite/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1185, in _inlineCallbacks
    result = g.send(result)
  File "/root/mysite/local/lib/python2.7/site-packages/scrapyd/poller.py", line 24, in poll
    returnValue(self.dq.put(self._message(msg, p)))
  File "/root/mysite/local/lib/python2.7/site-packages/scrapyd/poller.py", line 33, in _message
    d = queue_msg.copy()
exceptions.AttributeError: 'NoneType' object has no attribute 'copy'
```

**Comment by Digenis** [comment]
As  @shaneaevans said in the original ticket
`queue.pop()` returns `None`
if all rows are vanished
between the `queue.count` call and `queue.pop()`

In `queue.pop`, the line that returns `None`
is never executed in a typical scrapyd setup.

I think we should remove the `queue.count` call
and only check if q.pop returns None.
The only issue there is that q.pop is wrapped in a maybeDeferred
so we should first answer whether creating a deferred adds any significant overhead
compared to q.count.

**Comment by bezkos** [comment]
I used a similar condition like your @Digenis (basically the same in Python) for 2 days now and i dont have any errors like bug #40 anymore.
For the reference my condition between lines 23 and 24 in poller.py is:
if msg is None:                    
    return
else:
    returnValue(self.dq.put(self._message(msg, p)))

**Comment by Digenis** [comment]
I'm closing the issue since the bug is fixed.
The rest is just refactoring, for a later milestone.
