### ISSUE TITLE
`priority` is rejected as a spider argument

### ISSUE THREAD

**Issue by tanguilp** [scrapy/scrapyd#403]
`priority` is silently deleted when used as a spider argument.

It should be accepted, or at least documented.

**Comment by jpmckinney** [comment]
Aha, this is caused by #161. I suppose the solution will be documentation.

**Comment by atranou** [comment]
Hello! I'd like to make this documentation note. Is it still open?

**Comment by jpmckinney** [comment]
@atranou Yes, this issue is still open. Thank you!

**Comment by atranou** [comment]
Hello! 
This issue is resolved and merged: https://github.com/scrapy/scrapyd/pull/433

**Comment by jpmckinney** [comment]
Thank you!
