### ISSUE TITLE
apt-get install scrapyd doesn't work on Ubuntu #142

### ISSUE THREAD

**Issue by mtabbasi** [scrapy/scrapyd#404]
Per [the docs](https://scrapyd.readthedocs.io/en/stable/install.html) I'm trying

```
sudo apt-get install scrapyd
```
 
 in ubuntu 20.04 but get this error:
 
 > E: Unable to locate package scrapyd
 
 Is there a new package name that should be updated on the docs?

**Comment by my8100** [comment]
Try to execute `sudo apt update` first. 
BTW, why not use `pip install scrapyd` or pip3?

**Comment by mtabbasi** [comment]
> Try to execute `sudo apt update` first.
> BTW, why not use `pip install scrapyd` or pip3?
Same error after executing `sudo apt update`
Because it eases the administration work.

**Comment by jpmckinney** [comment]
These docs were removed in https://github.com/scrapy/scrapyd/commit/60039c76. ReadTheDocs hasn't yet been updated.
