### ISSUE TITLE
Can't create custom webservice through scrapyd

### ISSUE THREAD

**Issue by prostospirit** [scrapy/scrapyd#406]
I am trying to run multiple spiders at once and I made my own custom command in scrapy. Now I am trying to run that command through srapyd. I tried to add it as a new service to my scrapd.conf but it throws an error saying there is no such module.

Failed to load application: No module named XXXX

Also, I cannot set a relative path. My question is how can I add my custom command as a service or fire it through scrapyd. I have something like this in my scrapyd.conf:

updateoutdated.json = currentdirectory.myproject.command

**Comment by jpmckinney** [comment]
You will need to install the missing package(s) in the same environment as Scrapyd.

To avoid this step when using scrapyd-client, see this feature request: https://github.com/scrapy/scrapyd-client/issues/79
