### ISSUE TITLE
Print the release version when running with the "--version" flag.

### ISSUE THREAD

**Issue by saavedra29** [scrapy/scrapyd#415]
Wouldn't it be logical and convenient if the release version was printed when running `scrapyd --version`? Now it prints **only** the Twisted daemon version. In order to see the release version we have to navigate to the scrapyd's folder and see the VERSION file.

**Comment by niuguy** [comment]
@pawelmhm Is this issue still open? I'd like to work on it

**Comment by jpmckinney** [comment]
Yes, it is still open :)
