### ISSUE TITLE
Run tests on Windows & better Windows support

### ISSUE THREAD

**Issue by pawelmhm** [scrapy/scrapyd#417]
Before switching to github actions, we were not running tests on Windows as far as I know.

After switching to github actions most tests were passing on Windows, but coverage is not great, codecov shows around 70%. It is possible tests pass, but some things are not working on windows. 

When running windows tests in GitHub actions here https://github.com/scrapy/scrapyd/pull/411 I encountered some timeouts, need to figure out if they are related to codebase or to something in GitHub Actions. It would also be good to do some comprehensive testing on windows, users can report what works what doesn't. In my limited manual testing on windows ScrapyD seems to work, but I'm not a heavy windows user and didn't test all functionality. For now I switched off windows https://github.com/scrapy/scrapyd/pull/416/files

Similar things relate to pypy Python, also timeouts sometimes, except here when I run scrapyd locally with pypy I see some problems related to pyc files, need to look closer into this.

**Comment by jpmckinney** [comment]
Opened https://github.com/scrapy/scrapyd/pull/513 to see what fails.

**Comment by jpmckinney** [comment]
Done.
