### ISSUE TITLE
Authorization?

### ISSUE THREAD

**Issue by mattes** [scrapy/scrapyd#43]
Are there any plans concerning authorization of API requests?

**Comment by wvengen** [comment]
I'm not a Twisted expert, but I'd think it has a layer for http auth. Examples are [here](https://twistedmatrix.com/documents/current/web/howto/web-in-60/http-auth.html) and [here](http://www.tsheffler.com/blog/?p=502). If auth is desired, the [website Resource](https://github.com/scrapy/scrapyd/blob/master/scrapyd/website.py#L16) can then probably be wrapped in a [HTTPAuthSessionWrapper](https://twistedmatrix.com/documents/9.0.0/api/twisted.web.guard.HTTPAuthSessionWrapper.html).

**Comment by wvengen** [comment]
For those needing a solution now, you can of course always add a reverse proxy - like in [this gist]( https://gist.github.com/wvengen/ec5c795b0f2960d7ea07), which also adds SSL (not a luxury).

**Comment by lagenar** [comment]
Hi there, I see this one didn't get implemented. I'm a scrapyd user and it would be nice to have this feature. Are you willing to add accept a pull request for this one if I get to implement it?

**Comment by Digenis** [comment]
@lagenar, yes.
This or, even better, making scrapyd work with unix sockets
and let a webserver handle the authorization.
I think twisted allows it.

**Comment by syumdev** [comment]
Does anyone have any updates on this? Would love to get this feature.

**Comment by Digenis** [comment]
@syumdev, no, there's no update.
If you are familiar with twisted, perhaps you can make scrapyd listen on a unix socket.
This will make it possible to handle authentication through an apache on nginx proxy,
which offer a variety of authentication methods.

**Comment by my8100** [comment]
An alternative way to realize basic auth for Scrapyd https://stackoverflow.com/a/52852980/10517783

**Comment by Digenis** [comment]
Hi to everyone interested in this issue.
What are your thoughts on #325?

**Comment by my8100** [comment]
@Digenis, Still no plans to support built-in basic auth?

**Comment by Digenis** [comment]
If someone comes up with a decent PR, I would merge it.

**Comment by my8100** [comment]
@Digenis I make it in #326

**Comment by my8100** [comment]
@Digenis
This issue could be closed now.
