### ISSUE TITLE
jobs not being removed from running status

### ISSUE THREAD

**Issue by skagrawal10** [scrapy/scrapyd#435]
Hi, 

I am encountering one weird issue. When I am running docker container on my local instance, things are working fine but when I am running docker container on Google CloudRun, jobs are not being removed from "Running" status, though they are finished. I am not seeing any other errors from Scrapyd either. I am not using any kind drivers etc here. 
Any thoughts here will greatly appreciate.

**Comment by apramzhang** [comment]
I had the same problem

**Comment by jpmckinney** [comment]
Can you describe the precise steps to reproduce? I have not used Google CloudRun.

**Comment by jpmckinney** [comment]
Closing as no response.
