### ISSUE TITLE
API - add items and logs url to listjobs.json

### ISSUE THREAD

**Issue by mxdev88** [scrapy/scrapyd#464]
After making a call to listjobs.json, I'd like to download the items or logs related to the finished jobs. Would it make sense to add something like below?

2 new attributes:
* items_url 
* logs_url

```json
{
    "status": "ok",
    "pending": [],
    "running": [],
    "finished": [
        {
            "id": "2f16646cfcaf11e1b0090800272a6d06",
            "project": "myproject", "spider": "spider3",
            "start_time": "2012-09-12 10:14:03.594664",
            "end_time": "2012-09-12 10:24:03.594664",
            "items_url": "/items/myproject/spider3/2f16646cfcaf11e1b0090800272a6d06.jl",
            "log_url": "/logs/myproject/spider3/2f16646cfcaf11e1b0090800272a6d06.log"
        }
    ]
}
```

If so, I could submit a PR for it.

**Comment by jpmckinney** [comment]
That seems reasonable. That said, couldn't these URLs be constructed based on the available data?

**Comment by mxdev88** [comment]
That's true. Currently the client can build the url based on project, spider and job id but my reasoning here is that the client should be dumb and rely on the server to know where to locate the results. In case the logic is changed server side one day, it would be transparent. Makes sense?

**Comment by jpmckinney** [comment]
Yup, fine with me.
