### ISSUE TITLE
SQLite queue is using all CPU on high frequency poller (<1s)

### ISSUE THREAD

**Issue by pspsdev** [scrapy/scrapyd#475]
When running spiders that do nothing at all, the sqlite based poller uses all cpu just reading scheduled tasks. It would be good to have a plug and play alternative queues like redis.

**Comment by jpmckinney** [comment]
Why are you running spiders that "do nothing at all"?

**Comment by jpmckinney** [comment]
Hmm, yeah, same with https://github.com/Tiago-Lira/scrapyd-mongodb (from which scrapyd-redis is forked) and https://github.com/balena/python-pqueue (mentioned in #197).

https://github.com/peter-wangxu/persist-queue is still active, though maybe a first attempt is to switch to https://github.com/scrapy/queuelib as mentioned in #197.

Can you share your setup for reproducing the issue?

**Comment by jpmckinney** [comment]
@pspsdev Now that #476 is merged, do you have suggestions for how to edit the default spider queue, or should there just be a note in the documentation that it doesn't perform well under high frequency polling, and a custom queue would be better?

**Comment by jpmckinney** [comment]
FWIW, I can't replicate this issue. I set `poll_interval = 0.1` and scheduled 100 jobs in a loop.
