### ISSUE TITLE
Add support for environment variables

### ISSUE THREAD

**Issue by Shleif91** [scrapy/scrapyd#478]
Add support for environment variables. Very relevant for username and password

**Comment by jpmckinney** [comment]
What is the issue with storing the username/password in the configuration file?

**Comment by jpmckinney** [comment]
Duplicate #303

**Comment by therealpurplemana** [comment]
Would also like this feature. It is necessary for CI/CD deployment.

**Comment by jpmckinney** [comment]
You can do CI/CD deployment without Scrapyd having support for environment variables, like in https://github.com/scrapy/scrapyd/issues/303#issuecomment-926240350

**Comment by therealpurplemana** [comment]
Our scrapy script uploads to AWS S3. Wouldn't this method require writing our keys into a plaintext file?  Same for database writes in a middleware layer?

**Comment by jpmckinney** [comment]
Plaintext files like `/etc/shadow` or private SSH keys stored in `.ssh` directories are not inherently insecure. You can use the filesystem's permissions and ownership features to protect such files.

If an attacker gains root access to your server, they can just as easily run `cat /proc/PID/environ` to read the environment variables from any process (change `PID` to the process ID). Environment variables are not any more secure.

**Comment by jpmckinney** [comment]
Closing as need for envvar support (versus writing files) is unclear.
