### ISSUE TITLE
xxx.log can't be found

### ISSUE THREAD

**Issue by hyliush** [scrapy/scrapyd#479]
xxx/project/spider can be generated, but xxx.log can't be found

scrapy==2.8.0
scrapy-redis==0.7.3
scrapyd==1.3.0
scrapyd-client==1.2.2
scrapydweb==1.4.0

**Comment by jpmckinney** [comment]
I don't know what you mean. Can you be more specific?

**Comment by jxlil** [comment]
I didn't check this thoroughly, but in my case, when upgrading Scrapy (`2.6.0`-> `2.9.0`) scrapyd (`1.3.0`) stopped creating the `*.log` files

Updating srcapyd to version `1.4.1` seems to fix the bug.

**Comment by jpmckinney** [comment]
Ah, yes, scrapyd 1.4.0 adds support for scrapy 2.8. scrapy stopped recognizing the `SCRAPY_LOG_FILE` environment variable, so we switched to tthe `LOG_FILE` command-line argument.
