### ISSUE TITLE
Add reverse proxy support for web interface

### ISSUE THREAD

**Issue by TecIntelli** [scrapy/scrapyd#480]
I have written a small patch to use the Scrapyd web interface behind a reverse proxy with application specific base-path.
The path would be passed by a custom proxy header.

I have just modified the `website.py` and added a line to the `default_scrapyd.conf`. Of course I have also added some notes to the docs file `config.rst`.

What might be the easiest way to provide my tested patched files? Just open a pull request from a fork?

**Comment by jpmckinney** [comment]
Yes, a pull request from a fork would be easiest. Thank you for your contribution!
