### ISSUE TITLE
How to pause and resume crawling with scrapyd?

### ISSUE THREAD

**Issue by Akise** [scrapy/scrapyd#483]
I'd like to have persistence in my spider project while 
using scrapyd, but I don't quite know how exactly to do it.

**Comment by jpmckinney** [comment]
Pausing/resuming is a Scrapy feature, so you can do it as documented here: https://docs.scrapy.org/en/latest/topics/jobs.html#jobs-pausing-and-resuming-crawls

It would involve passing the JOBDIR setting when [scheduling the crawl](https://scrapyd.readthedocs.io/en/latest/api.html#schedule-json), e.g.

```
curl http://host/schedule.json -d project=myproject -d spider=somespider -d setting=JOBDIR=/path/to/dir
```

The [cancel](https://scrapyd.readthedocs.io/en/latest/api.html#cancel-json) endpoint does the same thing as Ctrl-C from Scrapy's documentation (i.e. sending the TERM signal).

**Comment by jpmckinney** [comment]
This is a Scrapy issue, not a Scrapyd issue. Scrapyd has no knowledge of Scrapy's JOBDIR features. It lets Scrapy manage the JOBDIR. Scrapyd is essentially just calling `scrapy crawl` with the spider settings you provide it via `-d setting=MYVAR=MYVALUE` like in my example command.
