### ISSUE TITLE
Use wheel files for deployment

### ISSUE THREAD

**Issue by majid-vaghari** [scrapy/scrapyd#488]
Hello, I'm new to scrapy and scrapyd. I've noticed that scrapyd uses Python egg formats for deploying new project versions.
Because I've never heard about egg files I did a little Google search and found out they've been replaced by the new wheel file formats:

> As of 2023, Python egg files have completely been replaced by wheel files which have a more defined and structured method of storing metadata and installation resources of python files.
    —from https://www.askpython.com/python/python-egg-file

So My question is why scrapyd still uses egg files? Is there a certain advantage to using them?

**Comment by jpmckinney** [comment]
https://packaging.python.org/en/latest/discussions/wheel-vs-egg/

> [Wheel](https://packaging.python.org/en/latest/glossary/#term-Wheel) is a [distribution](https://packaging.python.org/en/latest/glossary/#term-Distribution-Package) format, i.e a packaging format. [1](https://packaging.python.org/en/latest/discussions/wheel-vs-egg/#id3) [Egg](https://packaging.python.org/en/latest/glossary/#term-Egg) was both a distribution format and a runtime installation format (if left zipped), and was designed to be importable

We use eggs for the second reason, which wheels doesn’t cover.
