### ISSUE TITLE
May I ask is there any way use scrpyd to run python script with CrawlerProcess

### ISSUE THREAD

**Issue by xinatcg** [scrapy/scrapyd#489]
May I ask if is there any way use scrpyd to run Python script with CrawlerProcess

for example, the use case is: we have some custom logic for python script before run spider.

**Comment by jpmckinney** [comment]
Scrapyd essentially calls `scrapy crawl` on your project.

https://github.com/scrapy/scrapyd/blob/90b10234add797131996436cbba2ac4f3371de39/scrapyd/runner.py#L41-L45

https://github.com/scrapy/scrapyd/blob/90b10234add797131996436cbba2ac4f3371de39/scrapyd/launcher.py#L36-L49

Generally, you should be able to achieve anything you need by using the [spider_opened signal](https://docs.scrapy.org/en/latest/topics/signals.html#scrapy.signals.spider_opened).

If you're doing something very unusual, you'll have to share some example code for me to understand.

**Comment by xinatcg** [comment]
> Scrapyd essentially calls `scrapy crawl` on your project.
> 
> https://github.com/scrapy/scrapyd/blob/90b10234add797131996436cbba2ac4f3371de39/scrapyd/runner.py#L41-L45
> 
> https://github.com/scrapy/scrapyd/blob/90b10234add797131996436cbba2ac4f3371de39/scrapyd/launcher.py#L36-L49
> 
> Generally, you should be able to achieve anything you need by using the [spider_opened signal](https://docs.scrapy.org/en/latest/topics/signals.html#scrapy.signals.spider_opened).
> 
> If you're doing something very unusual, you'll have to share some example code for me to understand.

Thanks very much, we will have a look!
