### ISSUE TITLE
The work of scrapyd with the virtual environments of projects

### ISSUE THREAD

**Issue by WhatIsLowe** [scrapy/scrapyd#492]
How to implement the work of scrapyd with the virtual environments of my projects? 
For example, I have **scrapyd, scrapykeeper, scrapyd-client** installed in one virtual environment. Another virtual environment is used by my project.

**Comment by jpmckinney** [comment]
I'm not sure I understand? If you want scrapyd, scrapykeeper, scrapyd-client in your other virtual environment, just install them in that virtual environment.
