### ISSUE TITLE
Bad installation steps for "python setup.py install"

### ISSUE THREAD

**Issue by HyperUpscale** [scrapy/scrapyd#496]
It always installs the latest Twisted, and then the code checks and error: twisted 23.8.0 is installed but Twisted<23.8.0,>=18.9.0 is required by {'scrapy'}

**Comment by jpmckinney** [comment]
What version of pip are you using? `pip --version`

If you upgrade pip (`pip install -U pip`), then pip should resolve dependencies such that a correct version of twisted is installed.

**Comment by jpmckinney** [comment]
Closing, assuming 👍 means resolved.
