### ISSUE TITLE
Add status.json webservice to view status of specific job

### ISSUE THREAD

**Issue by egrachev** [scrapy/scrapyd#5]

**Comment by llonchj** [comment]
Sorry @pablohoffman, I am involved in a project that keeps me completely busy. Feel free to use all the code pushed many years ago

**Comment by jpmckinney** [comment]
I agree that this would be simpler than looking up a job id in the [listjobs.json](https://scrapyd.readthedocs.io/en/stable/api.html#listjobs-json) endpoint (which is what I do). That said, given limited maintainer capacity, I think it is best to focus on features that have no good alternative implementation outside Scrapyd.

**Comment by jpmckinney** [comment]
Re-opening since PR already exists: #260

**Comment by egrachev** [comment]
Thanks
