### ISSUE TITLE
Consider deprecated versions of Python3

### ISSUE THREAD

**Issue by vorenhoutgithub** [scrapy/scrapyd#508]
setup states it still supports deprecated or EOL Python 3

File: https://github.com/scrapy/scrapyd/blob/master/setup.py

Versions: https://devguide.python.org/versions/

Consider removing 3.7 and 3.8 from the list.

**Comment by jpmckinney** [comment]
Sure. Python 3.8 isn't EOL yet.

**Comment by vorenhoutgithub** [comment]
Thanks for picking this up so fast: very impressive and appreciated.
