### ISSUE TITLE
scrapyd deploy with slash in branch name causes problems

### ISSUE THREAD

**Issue by kevinkirkup** [scrapy/scrapyd#52]
If you try to deploy a project with scrapyd-deploy and your current branch has a slash in the name, it will say the deploy was successful, but doesn't update the project.

Example Branch Name: feature/some-feature

Changing the branch name solve the problem.

**Comment by Digenis** [comment]
@kevinkirkup,
I guess you deploy using git versioning instead of timestamp.
This is related to #117, slashes are also not escaped.

I'm closing this in favour of #117 which is more detailed.
