### ISSUE TITLE
chinese log encoding is error

### ISSUE THREAD

**Issue by mouday** [scrapy/scrapyd#532]
log file contains chinese words, browser show is error.

**Comment by jpmckinney** [comment]
You’ll have to provide steps to reproduce.

**Comment by mouday** [comment]
log file
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/6e2c042e-6856-4a01-89a4-351e2fdd4fa7">

chrome browser show log

<img width="1254" alt="image" src="https://github.com/user-attachments/assets/a1739850-4307-4f6f-bb07-665899112b3e">

**Comment by jpmckinney** [comment]
These aren’t steps to reproduce. Impossible to debug without steps to reproduce.
