### ISSUE TITLE
How to schedule a large amount of jobs and not overload server?

### ISSUE THREAD

**Issue by aaronm137** [scrapy/scrapyd#535]
I am experiencing a situation where I am sending thousands of `schedule` requests to schedule Scrapyd jobs and the server (Ubuntu) kills the scrapyd process, because it consumes a critical amount of memory (`oom killer`). To prevent that happening, I tried to wait a bit (using sleep) before adding a new `schedule.json` request. I am experimenting with setting the proper of sleep (0.1s, 0.25s, ...) to make it work. So far, unsuccessfuly.

I was testing something locally (Macbook M1) and I noticed that if I created onlu 8 `schedule.json` requests using `curl` from my terminal window, the scrapyd console ended up in an infinite loop. Out of curiousity, I didn't kill the process right away - I wanted to see when it will be killed by OSX. I came back in an hour and it was still looping, so I killed it manually.

My current workaround is experimenting with setting sleep time between the `schedule.json` requests and observing what's the magic sleep-figure to make it work. It's not optimal, though.

Hence my questions, what is the right/scrapyd-way to run thousands of `schedule.json` requests? (these requests are constructed in a loop of a data from the database and then the calls are made with curl).

**Comment by jpmckinney** [comment]
Can you share your Scrapyd configuration file?

Are you sending any data (spider arguments etc) with the schedule calls?

**Comment by aaronm137** [comment]
My `scrapyd.conf`:
```
[scrapyd]
eggs_dir    = eggs
logs_dir    = logs
items_dir   =
jobs_to_keep = 500
dbs_dir     = dbs
max_proc    = 0
#max_proc_per_cpu = 8
max_proc_per_cpu = 12
finished_to_keep = 100
#poll_interval = 5.0 # default
#poll_interval = 4.0
poll_interval = 1.0
bind_address = 0.0.0.0
http_port   = 6800
debug       = off
runner      = scrapyd.runner
application = scrapyd.app.application
launcher    = scrapyd.launcher.Launcher
ebroot     = scrapyd.website.Root

[services]
schedule.json     = scrapyd.webservice.Schedule
cancel.json       = scrapyd.webservice.Cancel
addversion.json   = scrapyd.webservice.AddVersion
listprojects.json = scrapyd.webservice.ListProjects
listversions.json = scrapyd.webservice.ListVersions
listspiders.json  = scrapyd.webservice.ListSpiders
delproject.json   = scrapyd.webservice.DeleteProject
delversion.json   = scrapyd.webservice.DeleteVersion
listjobs.json     = scrapyd.webservice.ListJobs
daemonstatus.json = scrapyd.webservice.DaemonStatus
```
As for sending data with the schedule calls - pretty much all of them look like this:
`curl http://127.0.0.1:6800/schedule.json -d project=my_proj -d spider=my_proj -d param_one=1 -d param_two=1 -d param_three=some-word -d param_four=2 -d priority=2.5`

Regarding measuring the memory usage per single "scrapy crawl" - how can I get it? I am fishing for this information in htop or Activity Monitor, but having difficulties to locate these processes.

**Comment by aaronm137** [comment]
Got it - the memusage is typically from `110MB` to `170MB`.
