### ISSUE TITLE
How to get the jobid returned when calling the /schedule.json interface in scrapy pipelines?

### ISSUE THREAD

**Issue by Teresajw** [scrapy/scrapyd#536]
I want to call the /schedule.json interface, return a jobid or pass in a jobid, and then when scheduling a job, I want to be able to get this ID in the pipelines, what do I need to do?

**Comment by jpmckinney** [comment]
From a spider class in Scrapy code, just do `self._job` to get the current job ID.

**Comment by Teresajw** [comment]
> From a spider class in Scrapy code, just do `self._job` to get the current job ID.

![image](https://github.com/user-attachments/assets/1079a4a9-6b3b-4f39-b0e7-638e20e365a6)
First of all, thank you for your answer, but calling self._id directly in pipelines prompts for not finding the

**Comment by jpmckinney** [comment]
Is the spider running within Scrapyd or not?

If you want to run the same code in both contexts, you can use the condition:

```python
if hasattr(spider, "_job"):
    print(self._job)
```

**Comment by jpmckinney** [comment]
And what version of Scrapyd are you using?

**Comment by Teresajw** [comment]
> ```python
> if hasattr(spider, "_job"):
>     print(self._job)
> ```

I'm calling jobid in pipeline, I'm using spider._job to get the value, thanks a lot!
