### ISSUE TITLE
Deprecation of projects without explicit Sphinx or MkDocs configuration

### ISSUE THREAD

**Issue by wRAR** [scrapy/scrapyd#537]
After **January 20, 2025**, Read the Docs will require explicit configuration for all Sphinx and MkDocs projects.

If you're using Sphinx or MkDocs, ensure your `.readthedocs.yaml` file includes the appropriate configuration key. For example:

For Sphinx projects:

    version: 2
    sphinx:
      configuration: docs/conf.py

**Comment by jpmckinney** [comment]
Fixed by 46a671f
