### ISSUE TITLE
custom downloader middleware not being deployed

### ISSUE THREAD

**Issue by localhosted** [scrapy/scrapyd#64]
My custom middleware isn't being deployed into the generated .egg, so the spiders fail to run when the class isn't found. More info here: http://stackoverflow.com/questions/25898851/importerror-error-loading-object-scrap-middlewares-randomuseragentmiddleware

**Comment by Digenis** [comment]
If it's not included in the .egg file then the discussion is for https://github.com/scrapy/scrapyd-client
The egg is really just a zipfile so you can check it yourself.

My guess is that you want to package into the egg something which is located elsewhere.
Where is your 'scrap' package located? Is it in the environment in which scrapyd is running?

**Comment by Digenis** [comment]
This is a missing documentation issue for scrapyd-client.
