### ISSUE TITLE
Spider stats webservice JSON format

### ISSUE THREAD

**Issue by MihaiCraciun** [scrapy/scrapyd#74]
How would one go about implementing a live feedback on what the spider is doing ? 
I have the logs that tell me each second pages per second and items, but i would like to access that via a webservice. 
Maybe I'm wrong, but I found in the scrapy docs that there is something that should do this http://localhost:6080/stats/spider_stats but it returns empty.
Any ideas are welcome.

Thanks!

edit: I would like to be able to do something like `curl http://localhost:6800/stats.json -d project=default -d spider=somespider`
and it would return `{"pages_crawled": "650","pages_per_min":"342","items_scraped":"286","items_per_min":"156"}`

**Comment by my8100** [comment]
Try [ScrapydWeb](https://github.com/my8100/scrapydweb), and get feedback via email.

**Comment by my8100** [comment]
1. Make sure that Scrapyd has been installed and started on the current host.
2. pip install logparser
3. Start [*LogParser*](https://github.com/my8100/logparser) via command `logparser`.
4. Visit http://127.0.0.1:6800/logs/stats.json (Assuming the Scrapyd service runs on port 6800.)
5. Visit http://127.0.0.1:6800/logs/projectname/spidername/jobid.json to get stats of a job in details.

**Comment by jpmckinney** [comment]
This feature is provided by logparser, rather than being added to scrapyd.
