### ISSUE TITLE
Getting the state of job on the basis of job id.

### ISSUE THREAD

**Issue by PramodBisht** [scrapy/scrapyd#76]
IMHO in scrapyd API, there should be some option to know the state of job like (pending, running and finished) on the basis of job id. Something like

result=scrapyd.state("job_id")

Thanks

**Comment by dfockler** [comment]
There is something like this [here](http://scrapyd.readthedocs.org/en/latest/api.html#listjobs-json).
It will return a JSON object of all the jobs, and you can find your job from there, in the pending, running, or finished array.

**Comment by Digenis** [comment]
duplicates #5
