### ISSUE TITLE
Arguments are urlencoded when passed to the spider

### ISSUE THREAD

**Issue by barraponto** [scrapy/scrapyd#77]
I was naively getting an argument from the command line and it was ok, but when I moved the project to scrapyd I noticed the arguments were being urlencoded when sent by python-requests. I needed to use `urlparse.unquote` to get the normalized argument.

**Comment by jayzeng** [comment]
@barraponto I am sure if I follow. What you described sounds reasonable to me, scrapyd runs over http and should be url encoded, if you rely on the output from scrapyd to trigger your own code, then you should unquote the results. Correct me if I am wrong, seems like I am missing something here.

**Comment by Digenis** [comment]
@barraponto, can you share an example, including code?

**Comment by barraponto** [comment]
Sorry, it's been a while. If I ever run into this again I'll reopen.
