### ISSUE TITLE
Add doc for development/contributing

### ISSUE THREAD

**Issue by dfockler** [scrapy/scrapyd#81]
It may be my Python inexperience, but I'm not sure how to get my modified scrapyd code to run from the project root, or how to run tests or anything. 
Any help would be appreciated, Thanks.

**Comment by jayzeng** [comment]
Sounds like you have pulled this repo to your local machine, you can do ```sudo python setup.py install```. And I agree we should have docs covered the details, interested in sending in a PR after you go through the entire process?

**Comment by jpmckinney** [comment]
This repo doesn't receive many contributions, so this is not a high priority.

That said, it is just:

```
git clone git@github.com:scrapy/scrapyd.git # or your fork
pip install -e .
pytest
```

So the same as any other Python package that uses pytest.

**Comment by jpmckinney** [comment]
Actually, the docs are here: https://scrapyd.readthedocs.io/en/stable/contributing.html
