### ISSUE TITLE
Install on debian ?

### ISSUE THREAD

**Issue by boogheta** [scrapy/scrapyd#82]
Hello,

There is a debian directory which is supposed to help build a package for debian but since the new version, the package requires installation of upstart which would break most debian installs. So I tried instead to install v0.17, but although it seems to install everything properly, when it's getting to the configuration part, it crashes while trying to start the daemon, which makes sense because it's trying to call /etc/init.d/scrapyd which is not a file anymore but a link to /lib/init/upstart-job which obviously does not exist.

Does anyone know how to properly install the scrapyd service on Debian ? (I know how to install via pip, running scrapyd manually, I need it as a daemon service as the former releases provided)

**Comment by dfockler** [comment]
This is for anyone else looking for this.
The ability to be daemonized is turned off in the CLI command when scrapyd is installed with pip. You need to run a `which scrapyd` see where that is, `cat` that file and you can see the `-n` added to the arguments which disables daemon mode in `twistd`. You should be able to delete the `-n` from the command list and be able to start scrapyd from the command line as a daemon. I'm not super familiar with Debian/Linux startup scripts, so if someone working on this project could comment, that would be great :)

**Comment by Digenis** [comment]
@boogheta, by "new version" do you mean debian8 or scrapyd1.1?

**Comment by boogheta** [comment]
I meant scrapyd 1.x

**Comment by Digenis** [comment]
The only relevant changes are #57 and #41,
the latter actually introducing the debian init script
so my question shouldn't have made sense.

You mean to say that the debian init script didn't work for you in the first place, right?

**Comment by jpmckinney** [comment]
Closing as no answer to clarification question for support request in 5 years.
