### ISSUE TITLE
scrapyd didn't inspect the config file in the users home directory

### ISSUE THREAD

**Issue by saibei88** [scrapy/scrapyd#94]
I haved installed scrapyd via pip.

And I created my costomized config file as `~/.scrapyd.conf`. But it didn't work.

I inspected `scrapyd/config.py`. It seems that the function didn't check `~/.scrapyd.conf`
``` python
    def _getsources(self):
        sources = ['/etc/scrapyd/scrapyd.conf', r'c:\scrapyd\scrapyd.conf']
        sources += sorted(glob.glob('/etc/scrapyd/conf.d/*'))
        sources += ['scrapyd.conf']
        scrapy_cfg = closest_scrapy_cfg()
        if scrapy_cfg:
            sources.append(scrapy_cfg)
        return sources
```

The verison of my scrapyd is 1.0.1

**Comment by Digenis** [comment]
0890d54be8e6aa8ec3eb4f94c7ac8720fb289791, which adds this feature,
first appeared on the 1.1 release.
You need to update your scrapyd version.
