### ISSUE TITLE
Scrapyd is not following links as per pattern given in "follow_patterns"

### ISSUE THREAD

**Issue by drprabhakar** [scrapy/scrapyd#95]
I am deploying my Portia spider in scrapyd. I have given a pattern to be followed in Crawling section in Portia. 
While deploying the spider, scrapyd is not following the link pattern which I have given.
How to fix this issue?

**Comment by bryant1410** [comment]
Does it work in scrapy (not scrapyd)?

**Comment by bgt-prabhakard** [comment]
I didn't check it with scrapy.
I am not good in scrapy so I have to go with Portia.
Is there any conditions mentioned in scrapyd or slybot to follow links?

**Comment by bryant1410** [comment]
This seems to be realted to scrapy, not scrapyd. Scrapyd is just a service to run scrapy spiders. Ask there
