### ISSUE TITLE
Using item exporters to export two items, the items don't seem to be created properly. 

### ISSUE THREAD

**Issue by mappelgren** [scrapy/scrapyd#99]
I have a spider that extracts two types of items. My item pipeline saves these in two separate files by using two item exporters (currently standard csv exporter). This approach creates the two files fine when just running scrapy crawl but either doesn't create them or I can't find them when using scrapyd schedule. I know that scrapyd is running my spider correctly, it returns correct status codes and also creates one file containing one type of item in json format. 

The psedo code of my pipeline is:

```
open_spider:
    file1 = open('filename1.csv','w')
    file2 = open('filename2.csv','w')
    exporter1 = CsvExporter(file1)
    exporter2 = CsvExporter(file2)

process_item(item):
    if isinstance(Item1,item):
        exporter1.export_item(item)
    else:
        exporter2.export_item(item)
```

I haven't changed any settings for scrapyd except the item_dir a few times. 

So, will scrapyd create files and what not in the same way as scrapy? Where will these be saved? Do I need to tell it to use my pipelines (its using them in scrapy)? Basically, I don't understand why it isn't working, please help. Thank you.

**Comment by Digenis** [comment]
In the spider's log, see if your pipeline is listed among the enabled ones.
In your pipeline, try logging the value of `os.path.abspath(file1.name)`

**Comment by Digenis** [comment]
Closing because of insufficient info
